import SwiftUI

/// The app's own glyphs: solid marks on a 24-unit grid, with their counters punched out by
/// the even-odd rule. A few carry a fat round-capped stroke where a line is unavoidable.
///
/// GENERATED by tools/generate_icons.py — edit the geometry there, not here, or the Kotlin
/// twin in ui/PoruchIcons.kt will drift away from this one.
///
/// A glyph carries no colour: `PoruchIcon` strokes and fills with the ambient foreground
/// style, so `.foregroundStyle(…)` at the call site works as it does for an SF Symbol.
struct PoruchGlyph {
    let stroke: ((inout Path, CGFloat) -> Void)?
    let fill: ((inout Path, CGFloat) -> Void)?
    /// One path whose inner subpaths punch holes through the outer one.
    let punch: ((inout Path, CGFloat) -> Void)?

    init(
        stroke: ((inout Path, CGFloat) -> Void)? = nil,
        fill: ((inout Path, CGFloat) -> Void)? = nil,
        punch: ((inout Path, CGFloat) -> Void)? = nil
    ) {
        self.stroke = stroke
        self.fill = fill
        self.punch = punch
    }
}

enum PoruchIcons {
    /// A solid eighth note. The flag is a crescent rather than a hooked line, so it keeps the weight of the head beside it.
    static let music = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(5.4, 16.9, s))
            path.addCurve(to: point(8.9, 13.4, s), control1: point(5.4, 14.967, s), control2: point(6.967, 13.4, s))
            path.addCurve(to: point(12.4, 16.9, s), control1: point(10.833, 13.4, s), control2: point(12.4, 14.967, s))
            path.addCurve(to: point(8.9, 20.4, s), control1: point(12.4, 18.833, s), control2: point(10.833, 20.4, s))
            path.addCurve(to: point(5.4, 16.9, s), control1: point(6.967, 20.4, s), control2: point(5.4, 18.833, s))
            path.closeSubpath()
            path.move(to: point(12.5, 5, s))
            path.addLine(to: point(12.5, 5, s))
            path.addCurve(to: point(13.5, 6, s), control1: point(13.052, 5, s), control2: point(13.5, 5.448, s))
            path.addLine(to: point(13.5, 16.2, s))
            path.addCurve(to: point(12.5, 17.2, s), control1: point(13.5, 16.752, s), control2: point(13.052, 17.2, s))
            path.addLine(to: point(12.5, 17.2, s))
            path.addCurve(to: point(11.5, 16.2, s), control1: point(11.948, 17.2, s), control2: point(11.5, 16.752, s))
            path.addLine(to: point(11.5, 6, s))
            path.addCurve(to: point(12.5, 5, s), control1: point(11.5, 5.448, s), control2: point(11.948, 5, s))
            path.closeSubpath()
            path.move(to: point(13.5, 5, s))
            path.addCurve(to: point(19, 10.9, s), control1: point(16.9, 6, s), control2: point(19, 8, s))
            path.addCurve(to: point(18.3, 13.3, s), control1: point(19, 11.8, s), control2: point(18.8, 12.6, s))
            path.addCurve(to: point(13.5, 7.7, s), control1: point(18.5, 10.4, s), control2: point(16.7, 8.6, s))
            path.closeSubpath()
        }
    )

    /// A solid pennant. A ball would be a third circle in a set that already has two, and thin seams across one read as a face at tile size.
    static let sport = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(6.9, 3.2, s))
            path.addLine(to: point(6.9, 3.2, s))
            path.addCurve(to: point(7.9, 4.2, s), control1: point(7.452, 3.2, s), control2: point(7.9, 3.648, s))
            path.addLine(to: point(7.9, 19.8, s))
            path.addCurve(to: point(6.9, 20.8, s), control1: point(7.9, 20.352, s), control2: point(7.452, 20.8, s))
            path.addLine(to: point(6.9, 20.8, s))
            path.addCurve(to: point(5.9, 19.8, s), control1: point(6.348, 20.8, s), control2: point(5.9, 20.352, s))
            path.addLine(to: point(5.9, 4.2, s))
            path.addCurve(to: point(6.9, 3.2, s), control1: point(5.9, 3.648, s), control2: point(6.348, 3.2, s))
            path.closeSubpath()
            path.move(to: point(7.9, 4.4, s))
            path.addLine(to: point(19.4, 8.1, s))
            path.addLine(to: point(7.9, 12.6, s))
            path.closeSubpath()
        }
    )

    /// A palette: a solid disc with four wells punched through it, the largest the thumb hole. Outlined wells on an outlined disc read as a bowling ball.
    static let art = PoruchGlyph(
        punch: { path, s in
            path.move(to: point(3.6, 12, s))
            path.addCurve(to: point(12, 3.6, s), control1: point(3.6, 7.361, s), control2: point(7.361, 3.6, s))
            path.addCurve(to: point(20.4, 12, s), control1: point(16.639, 3.6, s), control2: point(20.4, 7.361, s))
            path.addCurve(to: point(12, 20.4, s), control1: point(20.4, 16.639, s), control2: point(16.639, 20.4, s))
            path.addCurve(to: point(3.6, 12, s), control1: point(7.361, 20.4, s), control2: point(3.6, 16.639, s))
            path.closeSubpath()
            path.move(to: point(6.85, 9, s))
            path.addCurve(to: point(8.6, 7.25, s), control1: point(6.85, 8.034, s), control2: point(7.634, 7.25, s))
            path.addCurve(to: point(10.35, 9, s), control1: point(9.566, 7.25, s), control2: point(10.35, 8.034, s))
            path.addCurve(to: point(8.6, 10.75, s), control1: point(10.35, 9.966, s), control2: point(9.566, 10.75, s))
            path.addCurve(to: point(6.85, 9, s), control1: point(7.634, 10.75, s), control2: point(6.85, 9.966, s))
            path.closeSubpath()
            path.move(to: point(11.95, 7.9, s))
            path.addCurve(to: point(13.7, 6.15, s), control1: point(11.95, 6.934, s), control2: point(12.734, 6.15, s))
            path.addCurve(to: point(15.45, 7.9, s), control1: point(14.666, 6.15, s), control2: point(15.45, 6.934, s))
            path.addCurve(to: point(13.7, 9.65, s), control1: point(15.45, 8.866, s), control2: point(14.666, 9.65, s))
            path.addCurve(to: point(11.95, 7.9, s), control1: point(12.734, 9.65, s), control2: point(11.95, 8.866, s))
            path.closeSubpath()
            path.move(to: point(14.45, 12.5, s))
            path.addCurve(to: point(16.2, 10.75, s), control1: point(14.45, 11.534, s), control2: point(15.234, 10.75, s))
            path.addCurve(to: point(17.95, 12.5, s), control1: point(17.166, 10.75, s), control2: point(17.95, 11.534, s))
            path.addCurve(to: point(16.2, 14.25, s), control1: point(17.95, 13.466, s), control2: point(17.166, 14.25, s))
            path.addCurve(to: point(14.45, 12.5, s), control1: point(15.234, 14.25, s), control2: point(14.45, 13.466, s))
            path.closeSubpath()
            path.move(to: point(8.1, 15.9, s))
            path.addCurve(to: point(10.6, 13.4, s), control1: point(8.1, 14.519, s), control2: point(9.219, 13.4, s))
            path.addCurve(to: point(13.1, 15.9, s), control1: point(11.981, 13.4, s), control2: point(13.1, 14.519, s))
            path.addCurve(to: point(10.6, 18.4, s), control1: point(13.1, 17.281, s), control2: point(11.981, 18.4, s))
            path.addCurve(to: point(8.1, 15.9, s), control1: point(9.219, 18.4, s), control2: point(8.1, 17.281, s))
            path.closeSubpath()
        }
    )

    /// A solid bowl under two curls of steam. Cutlery at this size turns into two indistinguishable sticks.
    static let food = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(9.5, 8.5, s))
            path.addCurve(to: point(10.9, 4.9, s), control1: point(9.5, 7, s), control2: point(10.9, 6.5, s))
            path.move(to: point(14.1, 8.5, s))
            path.addCurve(to: point(15.5, 4.9, s), control1: point(14.1, 7, s), control2: point(15.5, 6.5, s))
        },
        fill: { path, s in
            path.move(to: point(4.2, 11, s))
            path.addLine(to: point(19.8, 11, s))
            path.addCurve(to: point(12, 19.7, s), control1: point(19.8, 15.8, s), control2: point(16.3, 19.7, s))
            path.addCurve(to: point(4.2, 11, s), control1: point(7.7, 19.7, s), control2: point(4.2, 15.8, s))
            path.closeSubpath()
        }
    )

    /// A die on its diagonal, pips punched out of the slab. A controller has too many small parts to survive shrinking to a map pin.
    static let games = PoruchGlyph(
        punch: { path, s in
            path.move(to: point(8.8, 4.4, s))
            path.addLine(to: point(15.2, 4.4, s))
            path.addCurve(to: point(19.6, 8.8, s), control1: point(17.63, 4.4, s), control2: point(19.6, 6.37, s))
            path.addLine(to: point(19.6, 15.2, s))
            path.addCurve(to: point(15.2, 19.6, s), control1: point(19.6, 17.63, s), control2: point(17.63, 19.6, s))
            path.addLine(to: point(8.8, 19.6, s))
            path.addCurve(to: point(4.4, 15.2, s), control1: point(6.37, 19.6, s), control2: point(4.4, 17.63, s))
            path.addLine(to: point(4.4, 8.8, s))
            path.addCurve(to: point(8.8, 4.4, s), control1: point(4.4, 6.37, s), control2: point(6.37, 4.4, s))
            path.closeSubpath()
            path.move(to: point(7.4, 9.1, s))
            path.addCurve(to: point(9.1, 7.4, s), control1: point(7.4, 8.161, s), control2: point(8.161, 7.4, s))
            path.addCurve(to: point(10.8, 9.1, s), control1: point(10.039, 7.4, s), control2: point(10.8, 8.161, s))
            path.addCurve(to: point(9.1, 10.8, s), control1: point(10.8, 10.039, s), control2: point(10.039, 10.8, s))
            path.addCurve(to: point(7.4, 9.1, s), control1: point(8.161, 10.8, s), control2: point(7.4, 10.039, s))
            path.closeSubpath()
            path.move(to: point(10.3, 12, s))
            path.addCurve(to: point(12, 10.3, s), control1: point(10.3, 11.061, s), control2: point(11.061, 10.3, s))
            path.addCurve(to: point(13.7, 12, s), control1: point(12.939, 10.3, s), control2: point(13.7, 11.061, s))
            path.addCurve(to: point(12, 13.7, s), control1: point(13.7, 12.939, s), control2: point(12.939, 13.7, s))
            path.addCurve(to: point(10.3, 12, s), control1: point(11.061, 13.7, s), control2: point(10.3, 12.939, s))
            path.closeSubpath()
            path.move(to: point(13.2, 14.9, s))
            path.addCurve(to: point(14.9, 13.2, s), control1: point(13.2, 13.961, s), control2: point(13.961, 13.2, s))
            path.addCurve(to: point(16.6, 14.9, s), control1: point(15.839, 13.2, s), control2: point(16.6, 13.961, s))
            path.addCurve(to: point(14.9, 16.6, s), control1: point(16.6, 15.839, s), control2: point(15.839, 16.6, s))
            path.addCurve(to: point(13.2, 14.9, s), control1: point(13.961, 16.6, s), control2: point(13.2, 15.839, s))
            path.closeSubpath()
        }
    )

    /// A pine as one solid silhouette with two tiers. A single triangle with a crossbar reads as the letter A.
    static let outdoors = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(12, 3.4, s))
            path.addLine(to: point(16.6, 11.2, s))
            path.addLine(to: point(14.5, 11.2, s))
            path.addLine(to: point(19, 18.2, s))
            path.addLine(to: point(5, 18.2, s))
            path.addLine(to: point(9.5, 11.2, s))
            path.addLine(to: point(7.4, 11.2, s))
            path.closeSubpath()
            path.move(to: point(12, 17.6, s))
            path.addLine(to: point(12, 17.6, s))
            path.addCurve(to: point(13, 18.6, s), control1: point(12.552, 17.6, s), control2: point(13, 18.048, s))
            path.addLine(to: point(13, 19.8, s))
            path.addCurve(to: point(12, 20.8, s), control1: point(13, 20.352, s), control2: point(12.552, 20.8, s))
            path.addLine(to: point(12, 20.8, s))
            path.addCurve(to: point(11, 19.8, s), control1: point(11.448, 20.8, s), control2: point(11, 20.352, s))
            path.addLine(to: point(11, 18.6, s))
            path.addCurve(to: point(12, 17.6, s), control1: point(11, 18.048, s), control2: point(11.448, 17.6, s))
            path.closeSubpath()
        }
    )

    /// Two solid figures, one behind the other: a gathering rather than a single profile.
    static let social = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(14, 9.4, s))
            path.addCurve(to: point(16.6, 6.8, s), control1: point(14, 7.964, s), control2: point(15.164, 6.8, s))
            path.addCurve(to: point(19.2, 9.4, s), control1: point(18.036, 6.8, s), control2: point(19.2, 7.964, s))
            path.addCurve(to: point(16.6, 12, s), control1: point(19.2, 10.836, s), control2: point(18.036, 12, s))
            path.addCurve(to: point(14, 9.4, s), control1: point(15.164, 12, s), control2: point(14, 10.836, s))
            path.closeSubpath()
            path.move(to: point(21, 19.8, s))
            path.addCurve(to: point(16.6, 13.7, s), control1: point(21, 15.9, s), control2: point(19.1, 13.7, s))
            path.addCurve(to: point(13.8, 14.7, s), control1: point(15.5, 13.7, s), control2: point(14.6, 14.1, s))
            path.addLine(to: point(13.8, 19.8, s))
            path.closeSubpath()
            path.move(to: point(5.9, 8.5, s))
            path.addCurve(to: point(9.3, 5.1, s), control1: point(5.9, 6.622, s), control2: point(7.422, 5.1, s))
            path.addCurve(to: point(12.7, 8.5, s), control1: point(11.178, 5.1, s), control2: point(12.7, 6.622, s))
            path.addCurve(to: point(9.3, 11.9, s), control1: point(12.7, 10.378, s), control2: point(11.178, 11.9, s))
            path.addCurve(to: point(5.9, 8.5, s), control1: point(7.422, 11.9, s), control2: point(5.9, 10.378, s))
            path.closeSubpath()
            path.move(to: point(2.6, 19.8, s))
            path.addCurve(to: point(9.3, 13.1, s), control1: point(2.6, 15.5, s), control2: point(5.4, 13.1, s))
            path.addCurve(to: point(16, 19.8, s), control1: point(13.2, 13.1, s), control2: point(16, 15.5, s))
            path.closeSubpath()
        }
    )

    /// A hand microphone: capsule, cradle, stand. Standup is named by its instrument the way music is by a note — a laughing mask would read as theatre, which is the very category comedy was split out of.
    static let comedy = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(6.9, 10.3, s))
            path.addCurve(to: point(12, 15.4, s), control1: point(6.9, 13.1, s), control2: point(9.2, 15.4, s))
            path.addCurve(to: point(17.1, 10.3, s), control1: point(14.8, 15.4, s), control2: point(17.1, 13.1, s))
        },
        fill: { path, s in
            path.move(to: point(12, 2.8, s))
            path.addLine(to: point(12, 2.8, s))
            path.addCurve(to: point(14.6, 5.4, s), control1: point(13.436, 2.8, s), control2: point(14.6, 3.964, s))
            path.addLine(to: point(14.6, 10.6, s))
            path.addCurve(to: point(12, 13.2, s), control1: point(14.6, 12.036, s), control2: point(13.436, 13.2, s))
            path.addLine(to: point(12, 13.2, s))
            path.addCurve(to: point(9.4, 10.6, s), control1: point(10.564, 13.2, s), control2: point(9.4, 12.036, s))
            path.addLine(to: point(9.4, 5.4, s))
            path.addCurve(to: point(12, 2.8, s), control1: point(9.4, 3.964, s), control2: point(10.564, 2.8, s))
            path.closeSubpath()
            path.move(to: point(12, 15, s))
            path.addLine(to: point(12, 15, s))
            path.addCurve(to: point(12.8, 15.8, s), control1: point(12.442, 15, s), control2: point(12.8, 15.358, s))
            path.addLine(to: point(12.8, 17.8, s))
            path.addCurve(to: point(12, 18.6, s), control1: point(12.8, 18.242, s), control2: point(12.442, 18.6, s))
            path.addLine(to: point(12, 18.6, s))
            path.addCurve(to: point(11.2, 17.8, s), control1: point(11.558, 18.6, s), control2: point(11.2, 18.242, s))
            path.addLine(to: point(11.2, 15.8, s))
            path.addCurve(to: point(12, 15, s), control1: point(11.2, 15.358, s), control2: point(11.558, 15, s))
            path.closeSubpath()
            path.move(to: point(9.4, 18, s))
            path.addLine(to: point(14.6, 18, s))
            path.addCurve(to: point(15.6, 19, s), control1: point(15.152, 18, s), control2: point(15.6, 18.448, s))
            path.addLine(to: point(15.6, 19, s))
            path.addCurve(to: point(14.6, 20, s), control1: point(15.6, 19.552, s), control2: point(15.152, 20, s))
            path.addLine(to: point(9.4, 20, s))
            path.addCurve(to: point(8.4, 19, s), control1: point(8.848, 20, s), control2: point(8.4, 19.552, s))
            path.addLine(to: point(8.4, 19, s))
            path.addCurve(to: point(9.4, 18, s), control1: point(8.4, 18.448, s), control2: point(8.848, 18, s))
            path.closeSubpath()
        }
    )

    /// A balloon on a string. Reads as «for children» at pin size, where a teddy or a kite collapses into a blob.
    static let kids = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(12, 15.6, s))
            path.addCurve(to: point(13.6, 20, s), control1: point(12, 17.4, s), control2: point(13.6, 18.2, s))
        },
        fill: { path, s in
            path.move(to: point(6, 9.2, s))
            path.addCurve(to: point(12, 3.2, s), control1: point(6, 5.886, s), control2: point(8.686, 3.2, s))
            path.addCurve(to: point(18, 9.2, s), control1: point(15.314, 3.2, s), control2: point(18, 5.886, s))
            path.addCurve(to: point(12, 15.2, s), control1: point(18, 12.514, s), control2: point(15.314, 15.2, s))
            path.addCurve(to: point(6, 9.2, s), control1: point(8.686, 15.2, s), control2: point(6, 12.514, s))
            path.closeSubpath()
            path.move(to: point(10.6, 14.6, s))
            path.addLine(to: point(13.4, 14.6, s))
            path.addLine(to: point(12, 16.4, s))
            path.closeSubpath()
        }
    )

    /// A solid house with the door punched through it — the negative space is what keeps the silhouette from reading as a plain pentagon.
    static let home = PoruchGlyph(
        punch: { path, s in
            path.move(to: point(12, 3, s))
            path.addLine(to: point(21.4, 11.6, s))
            path.addLine(to: point(18.7, 11.6, s))
            path.addLine(to: point(18.7, 20.8, s))
            path.addLine(to: point(5.3, 20.8, s))
            path.addLine(to: point(5.3, 11.6, s))
            path.addLine(to: point(2.6, 11.6, s))
            path.closeSubpath()
            path.move(to: point(11.6, 14.4, s))
            path.addLine(to: point(12.4, 14.4, s))
            path.addCurve(to: point(13.9, 15.9, s), control1: point(13.228, 14.4, s), control2: point(13.9, 15.072, s))
            path.addLine(to: point(13.9, 19.3, s))
            path.addCurve(to: point(12.4, 20.8, s), control1: point(13.9, 20.128, s), control2: point(13.228, 20.8, s))
            path.addLine(to: point(11.6, 20.8, s))
            path.addCurve(to: point(10.1, 19.3, s), control1: point(10.772, 20.8, s), control2: point(10.1, 20.128, s))
            path.addLine(to: point(10.1, 15.9, s))
            path.addCurve(to: point(11.6, 14.4, s), control1: point(10.1, 15.072, s), control2: point(10.772, 14.4, s))
            path.closeSubpath()
        }
    )

    /// Three solid panels with real gaps between them. Fold lines drawn as hairlines inside one shape disappear at tab-bar size.
    static let map = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(3.2, 6.4, s))
            path.addLine(to: point(8.3, 4.2, s))
            path.addLine(to: point(8.3, 17.6, s))
            path.addLine(to: point(3.2, 19.8, s))
            path.closeSubpath()
            path.move(to: point(9.5, 4.4, s))
            path.addLine(to: point(14.5, 6.8, s))
            path.addLine(to: point(14.5, 20.2, s))
            path.addLine(to: point(9.5, 17.8, s))
            path.closeSubpath()
            path.move(to: point(15.7, 6.8, s))
            path.addLine(to: point(20.8, 4.4, s))
            path.addLine(to: point(20.8, 17.8, s))
            path.addLine(to: point(15.7, 20.2, s))
            path.closeSubpath()
        }
    )

    /// A solid page with a month grid punched out under a header strip, and two hangers over the top.
    static let calendar = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(8.25, 2.2, s))
            path.addLine(to: point(8.25, 2.2, s))
            path.addCurve(to: point(9.3, 3.25, s), control1: point(8.83, 2.2, s), control2: point(9.3, 2.67, s))
            path.addLine(to: point(9.3, 5.75, s))
            path.addCurve(to: point(8.25, 6.8, s), control1: point(9.3, 6.33, s), control2: point(8.83, 6.8, s))
            path.addLine(to: point(8.25, 6.8, s))
            path.addCurve(to: point(7.2, 5.75, s), control1: point(7.67, 6.8, s), control2: point(7.2, 6.33, s))
            path.addLine(to: point(7.2, 3.25, s))
            path.addCurve(to: point(8.25, 2.2, s), control1: point(7.2, 2.67, s), control2: point(7.67, 2.2, s))
            path.closeSubpath()
            path.move(to: point(15.75, 2.2, s))
            path.addLine(to: point(15.75, 2.2, s))
            path.addCurve(to: point(16.8, 3.25, s), control1: point(16.33, 2.2, s), control2: point(16.8, 2.67, s))
            path.addLine(to: point(16.8, 5.75, s))
            path.addCurve(to: point(15.75, 6.8, s), control1: point(16.8, 6.33, s), control2: point(16.33, 6.8, s))
            path.addLine(to: point(15.75, 6.8, s))
            path.addCurve(to: point(14.7, 5.75, s), control1: point(15.17, 6.8, s), control2: point(14.7, 6.33, s))
            path.addLine(to: point(14.7, 3.25, s))
            path.addCurve(to: point(15.75, 2.2, s), control1: point(14.7, 2.67, s), control2: point(15.17, 2.2, s))
            path.closeSubpath()
        },
        punch: { path, s in
            path.move(to: point(7, 5.2, s))
            path.addLine(to: point(17, 5.2, s))
            path.addCurve(to: point(20.6, 8.8, s), control1: point(18.988, 5.2, s), control2: point(20.6, 6.812, s))
            path.addLine(to: point(20.6, 17.2, s))
            path.addCurve(to: point(17, 20.8, s), control1: point(20.6, 19.188, s), control2: point(18.988, 20.8, s))
            path.addLine(to: point(7, 20.8, s))
            path.addCurve(to: point(3.4, 17.2, s), control1: point(5.012, 20.8, s), control2: point(3.4, 19.188, s))
            path.addLine(to: point(3.4, 8.8, s))
            path.addCurve(to: point(7, 5.2, s), control1: point(3.4, 6.812, s), control2: point(5.012, 5.2, s))
            path.closeSubpath()
            path.move(to: point(7, 12.2, s))
            path.addLine(to: point(7.8, 12.2, s))
            path.addCurve(to: point(8.5, 12.9, s), control1: point(8.187, 12.2, s), control2: point(8.5, 12.513, s))
            path.addLine(to: point(8.5, 13.7, s))
            path.addCurve(to: point(7.8, 14.4, s), control1: point(8.5, 14.087, s), control2: point(8.187, 14.4, s))
            path.addLine(to: point(7, 14.4, s))
            path.addCurve(to: point(6.3, 13.7, s), control1: point(6.613, 14.4, s), control2: point(6.3, 14.087, s))
            path.addLine(to: point(6.3, 12.9, s))
            path.addCurve(to: point(7, 12.2, s), control1: point(6.3, 12.513, s), control2: point(6.613, 12.2, s))
            path.closeSubpath()
            path.move(to: point(11.6, 12.2, s))
            path.addLine(to: point(12.4, 12.2, s))
            path.addCurve(to: point(13.1, 12.9, s), control1: point(12.787, 12.2, s), control2: point(13.1, 12.513, s))
            path.addLine(to: point(13.1, 13.7, s))
            path.addCurve(to: point(12.4, 14.4, s), control1: point(13.1, 14.087, s), control2: point(12.787, 14.4, s))
            path.addLine(to: point(11.6, 14.4, s))
            path.addCurve(to: point(10.9, 13.7, s), control1: point(11.213, 14.4, s), control2: point(10.9, 14.087, s))
            path.addLine(to: point(10.9, 12.9, s))
            path.addCurve(to: point(11.6, 12.2, s), control1: point(10.9, 12.513, s), control2: point(11.213, 12.2, s))
            path.closeSubpath()
            path.move(to: point(16.2, 12.2, s))
            path.addLine(to: point(17, 12.2, s))
            path.addCurve(to: point(17.7, 12.9, s), control1: point(17.387, 12.2, s), control2: point(17.7, 12.513, s))
            path.addLine(to: point(17.7, 13.7, s))
            path.addCurve(to: point(17, 14.4, s), control1: point(17.7, 14.087, s), control2: point(17.387, 14.4, s))
            path.addLine(to: point(16.2, 14.4, s))
            path.addCurve(to: point(15.5, 13.7, s), control1: point(15.813, 14.4, s), control2: point(15.5, 14.087, s))
            path.addLine(to: point(15.5, 12.9, s))
            path.addCurve(to: point(16.2, 12.2, s), control1: point(15.5, 12.513, s), control2: point(15.813, 12.2, s))
            path.closeSubpath()
            path.move(to: point(7, 15.9, s))
            path.addLine(to: point(7.8, 15.9, s))
            path.addCurve(to: point(8.5, 16.6, s), control1: point(8.187, 15.9, s), control2: point(8.5, 16.213, s))
            path.addLine(to: point(8.5, 17.4, s))
            path.addCurve(to: point(7.8, 18.1, s), control1: point(8.5, 17.787, s), control2: point(8.187, 18.1, s))
            path.addLine(to: point(7, 18.1, s))
            path.addCurve(to: point(6.3, 17.4, s), control1: point(6.613, 18.1, s), control2: point(6.3, 17.787, s))
            path.addLine(to: point(6.3, 16.6, s))
            path.addCurve(to: point(7, 15.9, s), control1: point(6.3, 16.213, s), control2: point(6.613, 15.9, s))
            path.closeSubpath()
            path.move(to: point(11.6, 15.9, s))
            path.addLine(to: point(12.4, 15.9, s))
            path.addCurve(to: point(13.1, 16.6, s), control1: point(12.787, 15.9, s), control2: point(13.1, 16.213, s))
            path.addLine(to: point(13.1, 17.4, s))
            path.addCurve(to: point(12.4, 18.1, s), control1: point(13.1, 17.787, s), control2: point(12.787, 18.1, s))
            path.addLine(to: point(11.6, 18.1, s))
            path.addCurve(to: point(10.9, 17.4, s), control1: point(11.213, 18.1, s), control2: point(10.9, 17.787, s))
            path.addLine(to: point(10.9, 16.6, s))
            path.addCurve(to: point(11.6, 15.9, s), control1: point(10.9, 16.213, s), control2: point(11.213, 15.9, s))
            path.closeSubpath()
            path.move(to: point(16.2, 15.9, s))
            path.addLine(to: point(17, 15.9, s))
            path.addCurve(to: point(17.7, 16.6, s), control1: point(17.387, 15.9, s), control2: point(17.7, 16.213, s))
            path.addLine(to: point(17.7, 17.4, s))
            path.addCurve(to: point(17, 18.1, s), control1: point(17.7, 17.787, s), control2: point(17.387, 18.1, s))
            path.addLine(to: point(16.2, 18.1, s))
            path.addCurve(to: point(15.5, 17.4, s), control1: point(15.813, 18.1, s), control2: point(15.5, 17.787, s))
            path.addLine(to: point(15.5, 16.6, s))
            path.addCurve(to: point(16.2, 15.9, s), control1: point(15.5, 16.213, s), control2: point(15.813, 15.9, s))
            path.closeSubpath()
        }
    )

    /// Head and shoulders as two solid masses, open at the bottom so it sits on the baseline.
    static let person = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(8.3, 8.2, s))
            path.addCurve(to: point(12, 4.5, s), control1: point(8.3, 6.157, s), control2: point(9.957, 4.5, s))
            path.addCurve(to: point(15.7, 8.2, s), control1: point(14.043, 4.5, s), control2: point(15.7, 6.157, s))
            path.addCurve(to: point(12, 11.9, s), control1: point(15.7, 10.243, s), control2: point(14.043, 11.9, s))
            path.addCurve(to: point(8.3, 8.2, s), control1: point(9.957, 11.9, s), control2: point(8.3, 10.243, s))
            path.closeSubpath()
            path.move(to: point(4.4, 20.6, s))
            path.addCurve(to: point(12, 13.7, s), control1: point(4.4, 16.2, s), control2: point(7.8, 13.7, s))
            path.addCurve(to: point(19.6, 20.6, s), control1: point(16.2, 13.7, s), control2: point(19.6, 16.2, s))
            path.closeSubpath()
        }
    )

    /// A fat ring and a fat handle. The ring is punched rather than stroked so its weight matches the solid glyphs beside it.
    static let search = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(15.3, 15.3, s))
            path.addLine(to: point(19.9, 19.9, s))
        },
        punch: { path, s in
            path.move(to: point(3.4, 10.4, s))
            path.addCurve(to: point(10.4, 3.4, s), control1: point(3.4, 6.534, s), control2: point(6.534, 3.4, s))
            path.addCurve(to: point(17.4, 10.4, s), control1: point(14.266, 3.4, s), control2: point(17.4, 6.534, s))
            path.addCurve(to: point(10.4, 17.4, s), control1: point(17.4, 14.266, s), control2: point(14.266, 17.4, s))
            path.addCurve(to: point(3.4, 10.4, s), control1: point(6.534, 17.4, s), control2: point(3.4, 14.266, s))
            path.closeSubpath()
            path.move(to: point(6.4, 10.4, s))
            path.addCurve(to: point(10.4, 6.4, s), control1: point(6.4, 8.191, s), control2: point(8.191, 6.4, s))
            path.addCurve(to: point(14.4, 10.4, s), control1: point(12.609, 6.4, s), control2: point(14.4, 8.191, s))
            path.addCurve(to: point(10.4, 14.4, s), control1: point(14.4, 12.609, s), control2: point(12.609, 14.4, s))
            path.addCurve(to: point(6.4, 10.4, s), control1: point(8.191, 14.4, s), control2: point(6.4, 12.609, s))
            path.closeSubpath()
        }
    )

    /// Three narrowing slabs: filtering as a funnel, without the sliders Material draws.
    static let filters = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(4.65, 5.9, s))
            path.addLine(to: point(19.35, 5.9, s))
            path.addCurve(to: point(20.6, 7.15, s), control1: point(20.04, 5.9, s), control2: point(20.6, 6.46, s))
            path.addLine(to: point(20.6, 7.15, s))
            path.addCurve(to: point(19.35, 8.4, s), control1: point(20.6, 7.84, s), control2: point(20.04, 8.4, s))
            path.addLine(to: point(4.65, 8.4, s))
            path.addCurve(to: point(3.4, 7.15, s), control1: point(3.96, 8.4, s), control2: point(3.4, 7.84, s))
            path.addLine(to: point(3.4, 7.15, s))
            path.addCurve(to: point(4.65, 5.9, s), control1: point(3.4, 6.46, s), control2: point(3.96, 5.9, s))
            path.closeSubpath()
            path.move(to: point(7.35, 10.75, s))
            path.addLine(to: point(16.65, 10.75, s))
            path.addCurve(to: point(17.9, 12, s), control1: point(17.34, 10.75, s), control2: point(17.9, 11.31, s))
            path.addLine(to: point(17.9, 12, s))
            path.addCurve(to: point(16.65, 13.25, s), control1: point(17.9, 12.69, s), control2: point(17.34, 13.25, s))
            path.addLine(to: point(7.35, 13.25, s))
            path.addCurve(to: point(6.1, 12, s), control1: point(6.66, 13.25, s), control2: point(6.1, 12.69, s))
            path.addLine(to: point(6.1, 12, s))
            path.addCurve(to: point(7.35, 10.75, s), control1: point(6.1, 11.31, s), control2: point(6.66, 10.75, s))
            path.closeSubpath()
            path.move(to: point(10.15, 15.6, s))
            path.addLine(to: point(13.85, 15.6, s))
            path.addCurve(to: point(15.1, 16.85, s), control1: point(14.54, 15.6, s), control2: point(15.1, 16.16, s))
            path.addLine(to: point(15.1, 16.85, s))
            path.addCurve(to: point(13.85, 18.1, s), control1: point(15.1, 17.54, s), control2: point(14.54, 18.1, s))
            path.addLine(to: point(10.15, 18.1, s))
            path.addCurve(to: point(8.9, 16.85, s), control1: point(9.46, 18.1, s), control2: point(8.9, 17.54, s))
            path.addLine(to: point(8.9, 16.85, s))
            path.addCurve(to: point(10.15, 15.6, s), control1: point(8.9, 16.16, s), control2: point(9.46, 15.6, s))
            path.closeSubpath()
        }
    )

    /// A ribbon with its middle punched out, so the unsaved state is heavy without being solid.
    static let bookmark = PoruchGlyph(
        punch: { path, s in
            path.move(to: point(5.2, 3.2, s))
            path.addLine(to: point(18.8, 3.2, s))
            path.addLine(to: point(18.8, 21, s))
            path.addLine(to: point(12, 15.9, s))
            path.addLine(to: point(5.2, 21, s))
            path.closeSubpath()
            path.move(to: point(7.9, 5.9, s))
            path.addLine(to: point(16.1, 5.9, s))
            path.addLine(to: point(16.1, 15.6, s))
            path.addLine(to: point(12, 12.5, s))
            path.addLine(to: point(7.9, 15.6, s))
            path.closeSubpath()
        }
    )

    /// Saved: the same ribbon, filled in.
    static let bookmarkFilled = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(5.2, 3.2, s))
            path.addLine(to: point(18.8, 3.2, s))
            path.addLine(to: point(18.8, 21, s))
            path.addLine(to: point(12, 15.9, s))
            path.addLine(to: point(5.2, 21, s))
            path.closeSubpath()
        }
    )

    static let plus = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(12, 4.6, s))
            path.addLine(to: point(12, 4.6, s))
            path.addCurve(to: point(13.35, 5.95, s), control1: point(12.746, 4.6, s), control2: point(13.35, 5.204, s))
            path.addLine(to: point(13.35, 18.05, s))
            path.addCurve(to: point(12, 19.4, s), control1: point(13.35, 18.796, s), control2: point(12.746, 19.4, s))
            path.addLine(to: point(12, 19.4, s))
            path.addCurve(to: point(10.65, 18.05, s), control1: point(11.254, 19.4, s), control2: point(10.65, 18.796, s))
            path.addLine(to: point(10.65, 5.95, s))
            path.addCurve(to: point(12, 4.6, s), control1: point(10.65, 5.204, s), control2: point(11.254, 4.6, s))
            path.closeSubpath()
            path.move(to: point(5.95, 10.65, s))
            path.addLine(to: point(18.05, 10.65, s))
            path.addCurve(to: point(19.4, 12, s), control1: point(18.796, 10.65, s), control2: point(19.4, 11.254, s))
            path.addLine(to: point(19.4, 12, s))
            path.addCurve(to: point(18.05, 13.35, s), control1: point(19.4, 12.746, s), control2: point(18.796, 13.35, s))
            path.addLine(to: point(5.95, 13.35, s))
            path.addCurve(to: point(4.6, 12, s), control1: point(5.204, 13.35, s), control2: point(4.6, 12.746, s))
            path.addLine(to: point(4.6, 12, s))
            path.addCurve(to: point(5.95, 10.65, s), control1: point(4.6, 11.254, s), control2: point(5.204, 10.65, s))
            path.closeSubpath()
        }
    )

    /// The app's own mark at icon size: the launcher pin, the map pin and this glyph are one shape, down to the punched hole.
    static let pin = PoruchGlyph(
        punch: { path, s in
            path.move(to: point(12, 21, s))
            path.addCurve(to: point(4.6, 9.4, s), control1: point(12, 21, s), control2: point(4.6, 13.6, s))
            path.addCurve(to: point(12, 2.6, s), control1: point(4.6, 5.4, s), control2: point(7.9, 2.6, s))
            path.addCurve(to: point(19.4, 9.4, s), control1: point(16.1, 2.6, s), control2: point(19.4, 5.4, s))
            path.addCurve(to: point(12, 21, s), control1: point(19.4, 13.6, s), control2: point(12, 21, s))
            path.closeSubpath()
            path.move(to: point(9, 9.4, s))
            path.addCurve(to: point(12, 6.4, s), control1: point(9, 7.743, s), control2: point(10.343, 6.4, s))
            path.addCurve(to: point(15, 9.4, s), control1: point(13.657, 6.4, s), control2: point(15, 7.743, s))
            path.addCurve(to: point(12, 12.4, s), control1: point(15, 11.057, s), control2: point(13.657, 12.4, s))
            path.addCurve(to: point(9, 9.4, s), control1: point(10.343, 12.4, s), control2: point(9, 11.057, s))
            path.closeSubpath()
        }
    )

    /// A fat ring around a solid centre, with four ticks. The dot is what says «you».
    static let myLocation = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(10.1, 12, s))
            path.addCurve(to: point(12, 10.1, s), control1: point(10.1, 10.951, s), control2: point(10.951, 10.1, s))
            path.addCurve(to: point(13.9, 12, s), control1: point(13.049, 10.1, s), control2: point(13.9, 10.951, s))
            path.addCurve(to: point(12, 13.9, s), control1: point(13.9, 13.049, s), control2: point(13.049, 13.9, s))
            path.addCurve(to: point(10.1, 12, s), control1: point(10.951, 13.9, s), control2: point(10.1, 13.049, s))
            path.closeSubpath()
            path.move(to: point(12, 2.4, s))
            path.addLine(to: point(12, 2.4, s))
            path.addCurve(to: point(13, 3.4, s), control1: point(12.552, 2.4, s), control2: point(13, 2.848, s))
            path.addLine(to: point(13, 5, s))
            path.addCurve(to: point(12, 6, s), control1: point(13, 5.552, s), control2: point(12.552, 6, s))
            path.addLine(to: point(12, 6, s))
            path.addCurve(to: point(11, 5, s), control1: point(11.448, 6, s), control2: point(11, 5.552, s))
            path.addLine(to: point(11, 3.4, s))
            path.addCurve(to: point(12, 2.4, s), control1: point(11, 2.848, s), control2: point(11.448, 2.4, s))
            path.closeSubpath()
            path.move(to: point(12, 18, s))
            path.addLine(to: point(12, 18, s))
            path.addCurve(to: point(13, 19, s), control1: point(12.552, 18, s), control2: point(13, 18.448, s))
            path.addLine(to: point(13, 20.6, s))
            path.addCurve(to: point(12, 21.6, s), control1: point(13, 21.152, s), control2: point(12.552, 21.6, s))
            path.addLine(to: point(12, 21.6, s))
            path.addCurve(to: point(11, 20.6, s), control1: point(11.448, 21.6, s), control2: point(11, 21.152, s))
            path.addLine(to: point(11, 19, s))
            path.addCurve(to: point(12, 18, s), control1: point(11, 18.448, s), control2: point(11.448, 18, s))
            path.closeSubpath()
            path.move(to: point(3.4, 11, s))
            path.addLine(to: point(5, 11, s))
            path.addCurve(to: point(6, 12, s), control1: point(5.552, 11, s), control2: point(6, 11.448, s))
            path.addLine(to: point(6, 12, s))
            path.addCurve(to: point(5, 13, s), control1: point(6, 12.552, s), control2: point(5.552, 13, s))
            path.addLine(to: point(3.4, 13, s))
            path.addCurve(to: point(2.4, 12, s), control1: point(2.848, 13, s), control2: point(2.4, 12.552, s))
            path.addLine(to: point(2.4, 12, s))
            path.addCurve(to: point(3.4, 11, s), control1: point(2.4, 11.448, s), control2: point(2.848, 11, s))
            path.closeSubpath()
            path.move(to: point(19, 11, s))
            path.addLine(to: point(20.6, 11, s))
            path.addCurve(to: point(21.6, 12, s), control1: point(21.152, 11, s), control2: point(21.6, 11.448, s))
            path.addLine(to: point(21.6, 12, s))
            path.addCurve(to: point(20.6, 13, s), control1: point(21.6, 12.552, s), control2: point(21.152, 13, s))
            path.addLine(to: point(19, 13, s))
            path.addCurve(to: point(18, 12, s), control1: point(18.448, 13, s), control2: point(18, 12.552, s))
            path.addLine(to: point(18, 12, s))
            path.addCurve(to: point(19, 11, s), control1: point(18, 11.448, s), control2: point(18.448, 11, s))
            path.closeSubpath()
        },
        punch: { path, s in
            path.move(to: point(6.6, 12, s))
            path.addCurve(to: point(12, 6.6, s), control1: point(6.6, 9.018, s), control2: point(9.018, 6.6, s))
            path.addCurve(to: point(17.4, 12, s), control1: point(14.982, 6.6, s), control2: point(17.4, 9.018, s))
            path.addCurve(to: point(12, 17.4, s), control1: point(17.4, 14.982, s), control2: point(14.982, 17.4, s))
            path.addCurve(to: point(6.6, 12, s), control1: point(9.018, 17.4, s), control2: point(6.6, 14.982, s))
            path.closeSubpath()
            path.move(to: point(8.6, 12, s))
            path.addCurve(to: point(12, 8.6, s), control1: point(8.6, 10.122, s), control2: point(10.122, 8.6, s))
            path.addCurve(to: point(15.4, 12, s), control1: point(13.878, 8.6, s), control2: point(15.4, 10.122, s))
            path.addCurve(to: point(12, 15.4, s), control1: point(15.4, 13.878, s), control2: point(13.878, 15.4, s))
            path.addCurve(to: point(8.6, 12, s), control1: point(10.122, 15.4, s), control2: point(8.6, 13.878, s))
            path.closeSubpath()
        }
    )

    /// Four solid brackets closing on a dot: framing the city again after panning away.
    static let recenter = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(9.4, 12, s))
            path.addCurve(to: point(12, 9.4, s), control1: point(9.4, 10.564, s), control2: point(10.564, 9.4, s))
            path.addCurve(to: point(14.6, 12, s), control1: point(13.436, 9.4, s), control2: point(14.6, 10.564, s))
            path.addCurve(to: point(12, 14.6, s), control1: point(14.6, 13.436, s), control2: point(13.436, 14.6, s))
            path.addCurve(to: point(9.4, 12, s), control1: point(10.564, 14.6, s), control2: point(9.4, 13.436, s))
            path.closeSubpath()
            path.move(to: point(3.2, 9.6, s))
            path.addLine(to: point(3.2, 5.6, s))
            path.addCurve(to: point(5.6, 3.2, s), control1: point(3.2, 4.3, s), control2: point(4.3, 3.2, s))
            path.addLine(to: point(9.6, 3.2, s))
            path.addLine(to: point(9.6, 5.8, s))
            path.addLine(to: point(5.8, 5.8, s))
            path.addLine(to: point(5.8, 9.6, s))
            path.closeSubpath()
            path.move(to: point(20.8, 9.6, s))
            path.addLine(to: point(20.8, 5.6, s))
            path.addCurve(to: point(18.4, 3.2, s), control1: point(20.8, 4.3, s), control2: point(19.7, 3.2, s))
            path.addLine(to: point(14.4, 3.2, s))
            path.addLine(to: point(14.4, 5.8, s))
            path.addLine(to: point(18.2, 5.8, s))
            path.addLine(to: point(18.2, 9.6, s))
            path.closeSubpath()
            path.move(to: point(3.2, 14.4, s))
            path.addLine(to: point(3.2, 18.4, s))
            path.addCurve(to: point(5.6, 20.8, s), control1: point(3.2, 19.7, s), control2: point(4.3, 20.8, s))
            path.addLine(to: point(9.6, 20.8, s))
            path.addLine(to: point(9.6, 18.2, s))
            path.addLine(to: point(5.8, 18.2, s))
            path.addLine(to: point(5.8, 14.4, s))
            path.closeSubpath()
            path.move(to: point(20.8, 14.4, s))
            path.addLine(to: point(20.8, 18.4, s))
            path.addCurve(to: point(18.4, 20.8, s), control1: point(20.8, 19.7, s), control2: point(19.7, 20.8, s))
            path.addLine(to: point(14.4, 20.8, s))
            path.addLine(to: point(14.4, 18.2, s))
            path.addLine(to: point(18.2, 18.2, s))
            path.addLine(to: point(18.2, 14.4, s))
            path.closeSubpath()
        }
    )

    /// A four-point star with concave sides — an invitation, not a rating.
    static let sparkle = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(12, 2.8, s))
            path.addCurve(to: point(21.2, 12, s), control1: point(12.9, 8.7, s), control2: point(15.3, 11.1, s))
            path.addCurve(to: point(12, 21.2, s), control1: point(15.3, 12.9, s), control2: point(12.9, 15.3, s))
            path.addCurve(to: point(2.8, 12, s), control1: point(11.1, 15.3, s), control2: point(8.7, 12.9, s))
            path.addCurve(to: point(12, 2.8, s), control1: point(8.7, 11.1, s), control2: point(11.1, 8.7, s))
            path.closeSubpath()
        }
    )

    /// A solid body with the keyhole punched through, under a fat shackle.
    static let lock = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(8.3, 10.2, s))
            path.addLine(to: point(8.3, 7.8, s))
            path.addCurve(to: point(12, 4.1, s), control1: point(8.3, 5.7, s), control2: point(9.9, 4.1, s))
            path.addCurve(to: point(15.7, 7.8, s), control1: point(14.1, 4.1, s), control2: point(15.7, 5.7, s))
            path.addLine(to: point(15.7, 10.2, s))
        },
        punch: { path, s in
            path.move(to: point(7.8, 10.1, s))
            path.addLine(to: point(16.2, 10.1, s))
            path.addCurve(to: point(19.4, 13.3, s), control1: point(17.967, 10.1, s), control2: point(19.4, 11.533, s))
            path.addLine(to: point(19.4, 17.5, s))
            path.addCurve(to: point(16.2, 20.7, s), control1: point(19.4, 19.267, s), control2: point(17.967, 20.7, s))
            path.addLine(to: point(7.8, 20.7, s))
            path.addCurve(to: point(4.6, 17.5, s), control1: point(6.033, 20.7, s), control2: point(4.6, 19.267, s))
            path.addLine(to: point(4.6, 13.3, s))
            path.addCurve(to: point(7.8, 10.1, s), control1: point(4.6, 11.533, s), control2: point(6.033, 10.1, s))
            path.closeSubpath()
            path.move(to: point(10.3, 15.4, s))
            path.addCurve(to: point(12, 13.7, s), control1: point(10.3, 14.461, s), control2: point(11.061, 13.7, s))
            path.addCurve(to: point(13.7, 15.4, s), control1: point(12.939, 13.7, s), control2: point(13.7, 14.461, s))
            path.addCurve(to: point(12, 17.1, s), control1: point(13.7, 16.339, s), control2: point(12.939, 17.1, s))
            path.addCurve(to: point(10.3, 15.4, s), control1: point(11.061, 17.1, s), control2: point(10.3, 16.339, s))
            path.closeSubpath()
        }
    )

    static let checkCircle = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(8.2, 12.2, s))
            path.addLine(to: point(10.9, 14.9, s))
            path.addLine(to: point(15.9, 9.4, s))
        },
        punch: { path, s in
            path.move(to: point(3.4, 12, s))
            path.addCurve(to: point(12, 3.4, s), control1: point(3.4, 7.25, s), control2: point(7.25, 3.4, s))
            path.addCurve(to: point(20.6, 12, s), control1: point(16.75, 3.4, s), control2: point(20.6, 7.25, s))
            path.addCurve(to: point(12, 20.6, s), control1: point(20.6, 16.75, s), control2: point(16.75, 20.6, s))
            path.addCurve(to: point(3.4, 12, s), control1: point(7.25, 20.6, s), control2: point(3.4, 16.75, s))
            path.closeSubpath()
            path.move(to: point(5.8, 12, s))
            path.addCurve(to: point(12, 5.8, s), control1: point(5.8, 8.576, s), control2: point(8.576, 5.8, s))
            path.addCurve(to: point(18.2, 12, s), control1: point(15.424, 5.8, s), control2: point(18.2, 8.576, s))
            path.addCurve(to: point(12, 18.2, s), control1: point(18.2, 15.424, s), control2: point(15.424, 18.2, s))
            path.addCurve(to: point(5.8, 12, s), control1: point(8.576, 18.2, s), control2: point(5.8, 15.424, s))
            path.closeSubpath()
        }
    )

    static let alert = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(12, 7, s))
            path.addLine(to: point(12, 7, s))
            path.addCurve(to: point(13.3, 8.3, s), control1: point(12.718, 7, s), control2: point(13.3, 7.582, s))
            path.addLine(to: point(13.3, 12.3, s))
            path.addCurve(to: point(12, 13.6, s), control1: point(13.3, 13.018, s), control2: point(12.718, 13.6, s))
            path.addLine(to: point(12, 13.6, s))
            path.addCurve(to: point(10.7, 12.3, s), control1: point(11.282, 13.6, s), control2: point(10.7, 13.018, s))
            path.addLine(to: point(10.7, 8.3, s))
            path.addCurve(to: point(12, 7, s), control1: point(10.7, 7.582, s), control2: point(11.282, 7, s))
            path.closeSubpath()
            path.move(to: point(10.45, 16.4, s))
            path.addCurve(to: point(12, 14.85, s), control1: point(10.45, 15.544, s), control2: point(11.144, 14.85, s))
            path.addCurve(to: point(13.55, 16.4, s), control1: point(12.856, 14.85, s), control2: point(13.55, 15.544, s))
            path.addCurve(to: point(12, 17.95, s), control1: point(13.55, 17.256, s), control2: point(12.856, 17.95, s))
            path.addCurve(to: point(10.45, 16.4, s), control1: point(11.144, 17.95, s), control2: point(10.45, 17.256, s))
            path.closeSubpath()
        },
        punch: { path, s in
            path.move(to: point(3.4, 12, s))
            path.addCurve(to: point(12, 3.4, s), control1: point(3.4, 7.25, s), control2: point(7.25, 3.4, s))
            path.addCurve(to: point(20.6, 12, s), control1: point(16.75, 3.4, s), control2: point(20.6, 7.25, s))
            path.addCurve(to: point(12, 20.6, s), control1: point(20.6, 16.75, s), control2: point(16.75, 20.6, s))
            path.addCurve(to: point(3.4, 12, s), control1: point(7.25, 20.6, s), control2: point(3.4, 16.75, s))
            path.closeSubpath()
            path.move(to: point(5.8, 12, s))
            path.addCurve(to: point(12, 5.8, s), control1: point(5.8, 8.576, s), control2: point(8.576, 5.8, s))
            path.addCurve(to: point(18.2, 12, s), control1: point(15.424, 5.8, s), control2: point(18.2, 8.576, s))
            path.addCurve(to: point(12, 18.2, s), control1: point(18.2, 15.424, s), control2: point(15.424, 18.2, s))
            path.addCurve(to: point(5.8, 12, s), control1: point(8.576, 18.2, s), control2: point(5.8, 15.424, s))
            path.closeSubpath()
        }
    )

    static let clock = PoruchGlyph(
        stroke: { path, s in
            path.move(to: point(12, 7.4, s))
            path.addLine(to: point(12, 12, s))
            path.addLine(to: point(15.4, 14.1, s))
        },
        punch: { path, s in
            path.move(to: point(3.4, 12, s))
            path.addCurve(to: point(12, 3.4, s), control1: point(3.4, 7.25, s), control2: point(7.25, 3.4, s))
            path.addCurve(to: point(20.6, 12, s), control1: point(16.75, 3.4, s), control2: point(20.6, 7.25, s))
            path.addCurve(to: point(12, 20.6, s), control1: point(20.6, 16.75, s), control2: point(16.75, 20.6, s))
            path.addCurve(to: point(3.4, 12, s), control1: point(7.25, 20.6, s), control2: point(3.4, 16.75, s))
            path.closeSubpath()
            path.move(to: point(5.8, 12, s))
            path.addCurve(to: point(12, 5.8, s), control1: point(5.8, 8.576, s), control2: point(8.576, 5.8, s))
            path.addCurve(to: point(18.2, 12, s), control1: point(15.424, 5.8, s), control2: point(18.2, 8.576, s))
            path.addCurve(to: point(12, 18.2, s), control1: point(18.2, 15.424, s), control2: point(15.424, 18.2, s))
            path.addCurve(to: point(5.8, 12, s), control1: point(8.576, 18.2, s), control2: point(5.8, 15.424, s))
            path.closeSubpath()
        }
    )

    /// A solid hourglass for the waiting list: time passing, not an error.
    static let queue = PoruchGlyph(
        fill: { path, s in
            path.move(to: point(7.55, 3, s))
            path.addLine(to: point(16.45, 3, s))
            path.addCurve(to: point(17.6, 4.15, s), control1: point(17.085, 3, s), control2: point(17.6, 3.515, s))
            path.addLine(to: point(17.6, 4.15, s))
            path.addCurve(to: point(16.45, 5.3, s), control1: point(17.6, 4.785, s), control2: point(17.085, 5.3, s))
            path.addLine(to: point(7.55, 5.3, s))
            path.addCurve(to: point(6.4, 4.15, s), control1: point(6.915, 5.3, s), control2: point(6.4, 4.785, s))
            path.addLine(to: point(6.4, 4.15, s))
            path.addCurve(to: point(7.55, 3, s), control1: point(6.4, 3.515, s), control2: point(6.915, 3, s))
            path.closeSubpath()
            path.move(to: point(7.55, 18.7, s))
            path.addLine(to: point(16.45, 18.7, s))
            path.addCurve(to: point(17.6, 19.85, s), control1: point(17.085, 18.7, s), control2: point(17.6, 19.215, s))
            path.addLine(to: point(17.6, 19.85, s))
            path.addCurve(to: point(16.45, 21, s), control1: point(17.6, 20.485, s), control2: point(17.085, 21, s))
            path.addLine(to: point(7.55, 21, s))
            path.addCurve(to: point(6.4, 19.85, s), control1: point(6.915, 21, s), control2: point(6.4, 20.485, s))
            path.addLine(to: point(6.4, 19.85, s))
            path.addCurve(to: point(7.55, 18.7, s), control1: point(6.4, 19.215, s), control2: point(6.915, 18.7, s))
            path.closeSubpath()
            path.move(to: point(8.2, 5.3, s))
            path.addLine(to: point(15.8, 5.3, s))
            path.addLine(to: point(12.7, 12, s))
            path.addLine(to: point(15.8, 18.7, s))
            path.addLine(to: point(8.2, 18.7, s))
            path.addLine(to: point(11.3, 12, s))
            path.closeSubpath()
        }
    )

}

private func point(_ x: CGFloat, _ y: CGFloat, _ s: CGFloat) -> CGPoint {
    CGPoint(x: x * s, y: y * s)
}

/// Draws a [PoruchGlyph] at the given size, scaling the 24-unit grid and the stroke together.
struct PoruchIcon: View {
    let glyph: PoruchGlyph
    var size: CGFloat = 20

    var body: some View {
        ZStack {
            if glyph.punch != nil {
                GlyphShape(draw: glyph.punch).fill(style: FillStyle(eoFill: true))
            }
            if glyph.fill != nil {
                GlyphShape(draw: glyph.fill).fill()
            }
            if glyph.stroke != nil {
                GlyphShape(draw: glyph.stroke).stroke(style: StrokeStyle(
                    lineWidth: PoruchIconMetrics.stroke * scale,
                    lineCap: .round, lineJoin: .round
                ))
            }
        }
        .frame(width: size, height: size)
    }

    private var scale: CGFloat { size / PoruchIconMetrics.grid }
}

private struct GlyphShape: Shape {
    let draw: ((inout Path, CGFloat) -> Void)?

    func path(in rect: CGRect) -> Path {
        var path = Path()
        guard let draw else { return path }
        draw(&path, min(rect.width, rect.height) / PoruchIconMetrics.grid)
        return path
    }
}

enum PoruchIconMetrics {
    static let grid: CGFloat = 24
    static let stroke: CGFloat = 2.6
}
