package app.poruch.android.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * The app's own glyphs: solid marks on a 24-unit grid, with their counters punched out by
 * the even-odd rule. A few carry a fat round-capped stroke where a line is unavoidable.
 *
 * GENERATED by tools/generate_icons.py — edit the geometry there, not here, or the Swift
 * twin in DesignSystem/PoruchIcons.swift will drift away from this one.
 *
 * Everything is black: `Icon(tint = …)` recolours the whole vector, so baking a colour in
 * here would only fight the caller.
 */
object PoruchIcons {
    /** A solid eighth note. The flag is a crescent rather than a hooked line, so it keeps the weight of the head beside it. */
    val music: ImageVector by lazy {
        builder("music")
            .fill {
                moveTo(5.4f, 16.9f)
                curveTo(5.4f, 14.967f, 6.967f, 13.4f, 8.9f, 13.4f)
                curveTo(10.833f, 13.4f, 12.4f, 14.967f, 12.4f, 16.9f)
                curveTo(12.4f, 18.833f, 10.833f, 20.4f, 8.9f, 20.4f)
                curveTo(6.967f, 20.4f, 5.4f, 18.833f, 5.4f, 16.9f)
                close()
                moveTo(12.5f, 5f)
                lineTo(12.5f, 5f)
                curveTo(13.052f, 5f, 13.5f, 5.448f, 13.5f, 6f)
                lineTo(13.5f, 16.2f)
                curveTo(13.5f, 16.752f, 13.052f, 17.2f, 12.5f, 17.2f)
                lineTo(12.5f, 17.2f)
                curveTo(11.948f, 17.2f, 11.5f, 16.752f, 11.5f, 16.2f)
                lineTo(11.5f, 6f)
                curveTo(11.5f, 5.448f, 11.948f, 5f, 12.5f, 5f)
                close()
                moveTo(13.5f, 5f)
                curveTo(16.9f, 6f, 19f, 8f, 19f, 10.9f)
                curveTo(19f, 11.8f, 18.8f, 12.6f, 18.3f, 13.3f)
                curveTo(18.5f, 10.4f, 16.7f, 8.6f, 13.5f, 7.7f)
                close()
            }
            .build()
    }

    /** A solid pennant. A ball would be a third circle in a set that already has two, and thin seams across one read as a face at tile size. */
    val sport: ImageVector by lazy {
        builder("sport")
            .fill {
                moveTo(6.9f, 3.2f)
                lineTo(6.9f, 3.2f)
                curveTo(7.452f, 3.2f, 7.9f, 3.648f, 7.9f, 4.2f)
                lineTo(7.9f, 19.8f)
                curveTo(7.9f, 20.352f, 7.452f, 20.8f, 6.9f, 20.8f)
                lineTo(6.9f, 20.8f)
                curveTo(6.348f, 20.8f, 5.9f, 20.352f, 5.9f, 19.8f)
                lineTo(5.9f, 4.2f)
                curveTo(5.9f, 3.648f, 6.348f, 3.2f, 6.9f, 3.2f)
                close()
                moveTo(7.9f, 4.4f)
                lineTo(19.4f, 8.1f)
                lineTo(7.9f, 12.6f)
                close()
            }
            .build()
    }

    /** A palette: a solid disc with four wells punched through it, the largest the thumb hole. Outlined wells on an outlined disc read as a bowling ball. */
    val art: ImageVector by lazy {
        builder("art")
            .punch {
                moveTo(3.6f, 12f)
                curveTo(3.6f, 7.361f, 7.361f, 3.6f, 12f, 3.6f)
                curveTo(16.639f, 3.6f, 20.4f, 7.361f, 20.4f, 12f)
                curveTo(20.4f, 16.639f, 16.639f, 20.4f, 12f, 20.4f)
                curveTo(7.361f, 20.4f, 3.6f, 16.639f, 3.6f, 12f)
                close()
                moveTo(6.85f, 9f)
                curveTo(6.85f, 8.034f, 7.634f, 7.25f, 8.6f, 7.25f)
                curveTo(9.566f, 7.25f, 10.35f, 8.034f, 10.35f, 9f)
                curveTo(10.35f, 9.966f, 9.566f, 10.75f, 8.6f, 10.75f)
                curveTo(7.634f, 10.75f, 6.85f, 9.966f, 6.85f, 9f)
                close()
                moveTo(11.95f, 7.9f)
                curveTo(11.95f, 6.934f, 12.734f, 6.15f, 13.7f, 6.15f)
                curveTo(14.666f, 6.15f, 15.45f, 6.934f, 15.45f, 7.9f)
                curveTo(15.45f, 8.866f, 14.666f, 9.65f, 13.7f, 9.65f)
                curveTo(12.734f, 9.65f, 11.95f, 8.866f, 11.95f, 7.9f)
                close()
                moveTo(14.45f, 12.5f)
                curveTo(14.45f, 11.534f, 15.234f, 10.75f, 16.2f, 10.75f)
                curveTo(17.166f, 10.75f, 17.95f, 11.534f, 17.95f, 12.5f)
                curveTo(17.95f, 13.466f, 17.166f, 14.25f, 16.2f, 14.25f)
                curveTo(15.234f, 14.25f, 14.45f, 13.466f, 14.45f, 12.5f)
                close()
                moveTo(8.1f, 15.9f)
                curveTo(8.1f, 14.519f, 9.219f, 13.4f, 10.6f, 13.4f)
                curveTo(11.981f, 13.4f, 13.1f, 14.519f, 13.1f, 15.9f)
                curveTo(13.1f, 17.281f, 11.981f, 18.4f, 10.6f, 18.4f)
                curveTo(9.219f, 18.4f, 8.1f, 17.281f, 8.1f, 15.9f)
                close()
            }
            .build()
    }

    /** A solid bowl under two curls of steam. Cutlery at this size turns into two indistinguishable sticks. */
    val food: ImageVector by lazy {
        builder("food")
            .fill {
                moveTo(4.2f, 11f)
                lineTo(19.8f, 11f)
                curveTo(19.8f, 15.8f, 16.3f, 19.7f, 12f, 19.7f)
                curveTo(7.7f, 19.7f, 4.2f, 15.8f, 4.2f, 11f)
                close()
            }
            .stroke {
                moveTo(9.5f, 8.5f)
                curveTo(9.5f, 7f, 10.9f, 6.5f, 10.9f, 4.9f)
                moveTo(14.1f, 8.5f)
                curveTo(14.1f, 7f, 15.5f, 6.5f, 15.5f, 4.9f)
            }
            .build()
    }

    /** A die on its diagonal, pips punched out of the slab. A controller has too many small parts to survive shrinking to a map pin. */
    val games: ImageVector by lazy {
        builder("games")
            .punch {
                moveTo(8.8f, 4.4f)
                lineTo(15.2f, 4.4f)
                curveTo(17.63f, 4.4f, 19.6f, 6.37f, 19.6f, 8.8f)
                lineTo(19.6f, 15.2f)
                curveTo(19.6f, 17.63f, 17.63f, 19.6f, 15.2f, 19.6f)
                lineTo(8.8f, 19.6f)
                curveTo(6.37f, 19.6f, 4.4f, 17.63f, 4.4f, 15.2f)
                lineTo(4.4f, 8.8f)
                curveTo(4.4f, 6.37f, 6.37f, 4.4f, 8.8f, 4.4f)
                close()
                moveTo(7.4f, 9.1f)
                curveTo(7.4f, 8.161f, 8.161f, 7.4f, 9.1f, 7.4f)
                curveTo(10.039f, 7.4f, 10.8f, 8.161f, 10.8f, 9.1f)
                curveTo(10.8f, 10.039f, 10.039f, 10.8f, 9.1f, 10.8f)
                curveTo(8.161f, 10.8f, 7.4f, 10.039f, 7.4f, 9.1f)
                close()
                moveTo(10.3f, 12f)
                curveTo(10.3f, 11.061f, 11.061f, 10.3f, 12f, 10.3f)
                curveTo(12.939f, 10.3f, 13.7f, 11.061f, 13.7f, 12f)
                curveTo(13.7f, 12.939f, 12.939f, 13.7f, 12f, 13.7f)
                curveTo(11.061f, 13.7f, 10.3f, 12.939f, 10.3f, 12f)
                close()
                moveTo(13.2f, 14.9f)
                curveTo(13.2f, 13.961f, 13.961f, 13.2f, 14.9f, 13.2f)
                curveTo(15.839f, 13.2f, 16.6f, 13.961f, 16.6f, 14.9f)
                curveTo(16.6f, 15.839f, 15.839f, 16.6f, 14.9f, 16.6f)
                curveTo(13.961f, 16.6f, 13.2f, 15.839f, 13.2f, 14.9f)
                close()
            }
            .build()
    }

    /** A pine as one solid silhouette with two tiers. A single triangle with a crossbar reads as the letter A. */
    val outdoors: ImageVector by lazy {
        builder("outdoors")
            .fill {
                moveTo(12f, 3.4f)
                lineTo(16.6f, 11.2f)
                lineTo(14.5f, 11.2f)
                lineTo(19f, 18.2f)
                lineTo(5f, 18.2f)
                lineTo(9.5f, 11.2f)
                lineTo(7.4f, 11.2f)
                close()
                moveTo(12f, 17.6f)
                lineTo(12f, 17.6f)
                curveTo(12.552f, 17.6f, 13f, 18.048f, 13f, 18.6f)
                lineTo(13f, 19.8f)
                curveTo(13f, 20.352f, 12.552f, 20.8f, 12f, 20.8f)
                lineTo(12f, 20.8f)
                curveTo(11.448f, 20.8f, 11f, 20.352f, 11f, 19.8f)
                lineTo(11f, 18.6f)
                curveTo(11f, 18.048f, 11.448f, 17.6f, 12f, 17.6f)
                close()
            }
            .build()
    }

    /** Two solid figures, one behind the other: a gathering rather than a single profile. */
    val social: ImageVector by lazy {
        builder("social")
            .fill {
                moveTo(14f, 9.4f)
                curveTo(14f, 7.964f, 15.164f, 6.8f, 16.6f, 6.8f)
                curveTo(18.036f, 6.8f, 19.2f, 7.964f, 19.2f, 9.4f)
                curveTo(19.2f, 10.836f, 18.036f, 12f, 16.6f, 12f)
                curveTo(15.164f, 12f, 14f, 10.836f, 14f, 9.4f)
                close()
                moveTo(21f, 19.8f)
                curveTo(21f, 15.9f, 19.1f, 13.7f, 16.6f, 13.7f)
                curveTo(15.5f, 13.7f, 14.6f, 14.1f, 13.8f, 14.7f)
                lineTo(13.8f, 19.8f)
                close()
                moveTo(5.9f, 8.5f)
                curveTo(5.9f, 6.622f, 7.422f, 5.1f, 9.3f, 5.1f)
                curveTo(11.178f, 5.1f, 12.7f, 6.622f, 12.7f, 8.5f)
                curveTo(12.7f, 10.378f, 11.178f, 11.9f, 9.3f, 11.9f)
                curveTo(7.422f, 11.9f, 5.9f, 10.378f, 5.9f, 8.5f)
                close()
                moveTo(2.6f, 19.8f)
                curveTo(2.6f, 15.5f, 5.4f, 13.1f, 9.3f, 13.1f)
                curveTo(13.2f, 13.1f, 16f, 15.5f, 16f, 19.8f)
                close()
            }
            .build()
    }

    /** A hand microphone: capsule, cradle, stand. Standup is named by its instrument the way music is by a note — a laughing mask would read as theatre, which is the very category comedy was split out of. */
    val comedy: ImageVector by lazy {
        builder("comedy")
            .fill {
                moveTo(12f, 2.8f)
                lineTo(12f, 2.8f)
                curveTo(13.436f, 2.8f, 14.6f, 3.964f, 14.6f, 5.4f)
                lineTo(14.6f, 10.6f)
                curveTo(14.6f, 12.036f, 13.436f, 13.2f, 12f, 13.2f)
                lineTo(12f, 13.2f)
                curveTo(10.564f, 13.2f, 9.4f, 12.036f, 9.4f, 10.6f)
                lineTo(9.4f, 5.4f)
                curveTo(9.4f, 3.964f, 10.564f, 2.8f, 12f, 2.8f)
                close()
                moveTo(12f, 15f)
                lineTo(12f, 15f)
                curveTo(12.442f, 15f, 12.8f, 15.358f, 12.8f, 15.8f)
                lineTo(12.8f, 17.8f)
                curveTo(12.8f, 18.242f, 12.442f, 18.6f, 12f, 18.6f)
                lineTo(12f, 18.6f)
                curveTo(11.558f, 18.6f, 11.2f, 18.242f, 11.2f, 17.8f)
                lineTo(11.2f, 15.8f)
                curveTo(11.2f, 15.358f, 11.558f, 15f, 12f, 15f)
                close()
                moveTo(9.4f, 18f)
                lineTo(14.6f, 18f)
                curveTo(15.152f, 18f, 15.6f, 18.448f, 15.6f, 19f)
                lineTo(15.6f, 19f)
                curveTo(15.6f, 19.552f, 15.152f, 20f, 14.6f, 20f)
                lineTo(9.4f, 20f)
                curveTo(8.848f, 20f, 8.4f, 19.552f, 8.4f, 19f)
                lineTo(8.4f, 19f)
                curveTo(8.4f, 18.448f, 8.848f, 18f, 9.4f, 18f)
                close()
            }
            .stroke {
                moveTo(6.9f, 10.3f)
                curveTo(6.9f, 13.1f, 9.2f, 15.4f, 12f, 15.4f)
                curveTo(14.8f, 15.4f, 17.1f, 13.1f, 17.1f, 10.3f)
            }
            .build()
    }

    /** A balloon on a string. Reads as «for children» at pin size, where a teddy or a kite collapses into a blob. */
    val kids: ImageVector by lazy {
        builder("kids")
            .fill {
                moveTo(6f, 9.2f)
                curveTo(6f, 5.886f, 8.686f, 3.2f, 12f, 3.2f)
                curveTo(15.314f, 3.2f, 18f, 5.886f, 18f, 9.2f)
                curveTo(18f, 12.514f, 15.314f, 15.2f, 12f, 15.2f)
                curveTo(8.686f, 15.2f, 6f, 12.514f, 6f, 9.2f)
                close()
                moveTo(10.6f, 14.6f)
                lineTo(13.4f, 14.6f)
                lineTo(12f, 16.4f)
                close()
            }
            .stroke {
                moveTo(12f, 15.6f)
                curveTo(12f, 17.4f, 13.6f, 18.2f, 13.6f, 20f)
            }
            .build()
    }

    /** Брама зі склепінням. Перший варіант був вимпелом гіда — і на рендері виявився тим самим прапорцем, що вже стоїть у «спорті»: на піні їх не розрізнити. Арка ж збігається зі змістом кошика: вілли, катедри, вежі, кам'яниці. */
    val tours: ImageVector by lazy {
        builder("tours")
            .punch {
                moveTo(3.4f, 20.9f)
                lineTo(3.4f, 11.5f)
                curveTo(3.4f, 6.8f, 7.3f, 3f, 12f, 3f)
                curveTo(16.7f, 3f, 20.6f, 6.8f, 20.6f, 11.5f)
                lineTo(20.6f, 20.9f)
                close()
                moveTo(8f, 20.9f)
                lineTo(8f, 11.8f)
                curveTo(8f, 9.2f, 9.8f, 7.3f, 12f, 7.3f)
                curveTo(14.2f, 7.3f, 16f, 9.2f, 16f, 11.8f)
                lineTo(16f, 20.9f)
                close()
            }
            .build()
    }

    /** A slide on a stand. Distinct from the calendar glyph, which carries a month grid and two hangers; here the board is wide, the text lines are long, and it stands on a foot. */
    val conference: ImageVector by lazy {
        builder("conference")
            .punch {
                moveTo(5.6f, 3.3f)
                lineTo(18.4f, 3.3f)
                curveTo(19.67f, 3.3f, 20.7f, 4.33f, 20.7f, 5.6f)
                lineTo(20.7f, 13.5f)
                curveTo(20.7f, 14.77f, 19.67f, 15.8f, 18.4f, 15.8f)
                lineTo(5.6f, 15.8f)
                curveTo(4.33f, 15.8f, 3.3f, 14.77f, 3.3f, 13.5f)
                lineTo(3.3f, 5.6f)
                curveTo(3.3f, 4.33f, 4.33f, 3.3f, 5.6f, 3.3f)
                close()
                moveTo(7.4f, 6.9f)
                lineTo(16.5f, 6.9f)
                curveTo(16.997f, 6.9f, 17.4f, 7.303f, 17.4f, 7.8f)
                lineTo(17.4f, 7.8f)
                curveTo(17.4f, 8.297f, 16.997f, 8.7f, 16.5f, 8.7f)
                lineTo(7.4f, 8.7f)
                curveTo(6.903f, 8.7f, 6.5f, 8.297f, 6.5f, 7.8f)
                lineTo(6.5f, 7.8f)
                curveTo(6.5f, 7.303f, 6.903f, 6.9f, 7.4f, 6.9f)
                close()
                moveTo(7.4f, 10.5f)
                lineTo(12.7f, 10.5f)
                curveTo(13.197f, 10.5f, 13.6f, 10.903f, 13.6f, 11.4f)
                lineTo(13.6f, 11.4f)
                curveTo(13.6f, 11.897f, 13.197f, 12.3f, 12.7f, 12.3f)
                lineTo(7.4f, 12.3f)
                curveTo(6.903f, 12.3f, 6.5f, 11.897f, 6.5f, 11.4f)
                lineTo(6.5f, 11.4f)
                curveTo(6.5f, 10.903f, 6.903f, 10.5f, 7.4f, 10.5f)
                close()
            }
            .fill {
                moveTo(12f, 15.8f)
                lineTo(12f, 15.8f)
                curveTo(12.497f, 15.8f, 12.9f, 16.203f, 12.9f, 16.7f)
                lineTo(12.9f, 18.2f)
                curveTo(12.9f, 18.697f, 12.497f, 19.1f, 12f, 19.1f)
                lineTo(12f, 19.1f)
                curveTo(11.503f, 19.1f, 11.1f, 18.697f, 11.1f, 18.2f)
                lineTo(11.1f, 16.7f)
                curveTo(11.1f, 16.203f, 11.503f, 15.8f, 12f, 15.8f)
                close()
                moveTo(8.15f, 18.9f)
                lineTo(15.85f, 18.9f)
                curveTo(16.319f, 18.9f, 16.7f, 19.281f, 16.7f, 19.75f)
                lineTo(16.7f, 19.75f)
                curveTo(16.7f, 20.219f, 16.319f, 20.6f, 15.85f, 20.6f)
                lineTo(8.15f, 20.6f)
                curveTo(7.681f, 20.6f, 7.3f, 20.219f, 7.3f, 19.75f)
                lineTo(7.3f, 19.75f)
                curveTo(7.3f, 19.281f, 7.681f, 18.9f, 8.15f, 18.9f)
                close()
            }
            .build()
    }

    /** A solid house with the door punched through it — the negative space is what keeps the silhouette from reading as a plain pentagon. */
    val home: ImageVector by lazy {
        builder("home")
            .punch {
                moveTo(12f, 3f)
                lineTo(21.4f, 11.6f)
                lineTo(18.7f, 11.6f)
                lineTo(18.7f, 20.8f)
                lineTo(5.3f, 20.8f)
                lineTo(5.3f, 11.6f)
                lineTo(2.6f, 11.6f)
                close()
                moveTo(11.6f, 14.4f)
                lineTo(12.4f, 14.4f)
                curveTo(13.228f, 14.4f, 13.9f, 15.072f, 13.9f, 15.9f)
                lineTo(13.9f, 19.3f)
                curveTo(13.9f, 20.128f, 13.228f, 20.8f, 12.4f, 20.8f)
                lineTo(11.6f, 20.8f)
                curveTo(10.772f, 20.8f, 10.1f, 20.128f, 10.1f, 19.3f)
                lineTo(10.1f, 15.9f)
                curveTo(10.1f, 15.072f, 10.772f, 14.4f, 11.6f, 14.4f)
                close()
            }
            .build()
    }

    /** Three solid panels with real gaps between them. Fold lines drawn as hairlines inside one shape disappear at tab-bar size. */
    val map: ImageVector by lazy {
        builder("map")
            .fill {
                moveTo(3.2f, 6.4f)
                lineTo(8.3f, 4.2f)
                lineTo(8.3f, 17.6f)
                lineTo(3.2f, 19.8f)
                close()
                moveTo(9.5f, 4.4f)
                lineTo(14.5f, 6.8f)
                lineTo(14.5f, 20.2f)
                lineTo(9.5f, 17.8f)
                close()
                moveTo(15.7f, 6.8f)
                lineTo(20.8f, 4.4f)
                lineTo(20.8f, 17.8f)
                lineTo(15.7f, 20.2f)
                close()
            }
            .build()
    }

    /** A solid page with a month grid punched out under a header strip, and two hangers over the top. */
    val calendar: ImageVector by lazy {
        builder("calendar")
            .punch {
                moveTo(7f, 5.2f)
                lineTo(17f, 5.2f)
                curveTo(18.988f, 5.2f, 20.6f, 6.812f, 20.6f, 8.8f)
                lineTo(20.6f, 17.2f)
                curveTo(20.6f, 19.188f, 18.988f, 20.8f, 17f, 20.8f)
                lineTo(7f, 20.8f)
                curveTo(5.012f, 20.8f, 3.4f, 19.188f, 3.4f, 17.2f)
                lineTo(3.4f, 8.8f)
                curveTo(3.4f, 6.812f, 5.012f, 5.2f, 7f, 5.2f)
                close()
                moveTo(7f, 12.2f)
                lineTo(7.8f, 12.2f)
                curveTo(8.187f, 12.2f, 8.5f, 12.513f, 8.5f, 12.9f)
                lineTo(8.5f, 13.7f)
                curveTo(8.5f, 14.087f, 8.187f, 14.4f, 7.8f, 14.4f)
                lineTo(7f, 14.4f)
                curveTo(6.613f, 14.4f, 6.3f, 14.087f, 6.3f, 13.7f)
                lineTo(6.3f, 12.9f)
                curveTo(6.3f, 12.513f, 6.613f, 12.2f, 7f, 12.2f)
                close()
                moveTo(11.6f, 12.2f)
                lineTo(12.4f, 12.2f)
                curveTo(12.787f, 12.2f, 13.1f, 12.513f, 13.1f, 12.9f)
                lineTo(13.1f, 13.7f)
                curveTo(13.1f, 14.087f, 12.787f, 14.4f, 12.4f, 14.4f)
                lineTo(11.6f, 14.4f)
                curveTo(11.213f, 14.4f, 10.9f, 14.087f, 10.9f, 13.7f)
                lineTo(10.9f, 12.9f)
                curveTo(10.9f, 12.513f, 11.213f, 12.2f, 11.6f, 12.2f)
                close()
                moveTo(16.2f, 12.2f)
                lineTo(17f, 12.2f)
                curveTo(17.387f, 12.2f, 17.7f, 12.513f, 17.7f, 12.9f)
                lineTo(17.7f, 13.7f)
                curveTo(17.7f, 14.087f, 17.387f, 14.4f, 17f, 14.4f)
                lineTo(16.2f, 14.4f)
                curveTo(15.813f, 14.4f, 15.5f, 14.087f, 15.5f, 13.7f)
                lineTo(15.5f, 12.9f)
                curveTo(15.5f, 12.513f, 15.813f, 12.2f, 16.2f, 12.2f)
                close()
                moveTo(7f, 15.9f)
                lineTo(7.8f, 15.9f)
                curveTo(8.187f, 15.9f, 8.5f, 16.213f, 8.5f, 16.6f)
                lineTo(8.5f, 17.4f)
                curveTo(8.5f, 17.787f, 8.187f, 18.1f, 7.8f, 18.1f)
                lineTo(7f, 18.1f)
                curveTo(6.613f, 18.1f, 6.3f, 17.787f, 6.3f, 17.4f)
                lineTo(6.3f, 16.6f)
                curveTo(6.3f, 16.213f, 6.613f, 15.9f, 7f, 15.9f)
                close()
                moveTo(11.6f, 15.9f)
                lineTo(12.4f, 15.9f)
                curveTo(12.787f, 15.9f, 13.1f, 16.213f, 13.1f, 16.6f)
                lineTo(13.1f, 17.4f)
                curveTo(13.1f, 17.787f, 12.787f, 18.1f, 12.4f, 18.1f)
                lineTo(11.6f, 18.1f)
                curveTo(11.213f, 18.1f, 10.9f, 17.787f, 10.9f, 17.4f)
                lineTo(10.9f, 16.6f)
                curveTo(10.9f, 16.213f, 11.213f, 15.9f, 11.6f, 15.9f)
                close()
                moveTo(16.2f, 15.9f)
                lineTo(17f, 15.9f)
                curveTo(17.387f, 15.9f, 17.7f, 16.213f, 17.7f, 16.6f)
                lineTo(17.7f, 17.4f)
                curveTo(17.7f, 17.787f, 17.387f, 18.1f, 17f, 18.1f)
                lineTo(16.2f, 18.1f)
                curveTo(15.813f, 18.1f, 15.5f, 17.787f, 15.5f, 17.4f)
                lineTo(15.5f, 16.6f)
                curveTo(15.5f, 16.213f, 15.813f, 15.9f, 16.2f, 15.9f)
                close()
            }
            .fill {
                moveTo(8.25f, 2.2f)
                lineTo(8.25f, 2.2f)
                curveTo(8.83f, 2.2f, 9.3f, 2.67f, 9.3f, 3.25f)
                lineTo(9.3f, 5.75f)
                curveTo(9.3f, 6.33f, 8.83f, 6.8f, 8.25f, 6.8f)
                lineTo(8.25f, 6.8f)
                curveTo(7.67f, 6.8f, 7.2f, 6.33f, 7.2f, 5.75f)
                lineTo(7.2f, 3.25f)
                curveTo(7.2f, 2.67f, 7.67f, 2.2f, 8.25f, 2.2f)
                close()
                moveTo(15.75f, 2.2f)
                lineTo(15.75f, 2.2f)
                curveTo(16.33f, 2.2f, 16.8f, 2.67f, 16.8f, 3.25f)
                lineTo(16.8f, 5.75f)
                curveTo(16.8f, 6.33f, 16.33f, 6.8f, 15.75f, 6.8f)
                lineTo(15.75f, 6.8f)
                curveTo(15.17f, 6.8f, 14.7f, 6.33f, 14.7f, 5.75f)
                lineTo(14.7f, 3.25f)
                curveTo(14.7f, 2.67f, 15.17f, 2.2f, 15.75f, 2.2f)
                close()
            }
            .build()
    }

    /** Head and shoulders as two solid masses, open at the bottom so it sits on the baseline. */
    val person: ImageVector by lazy {
        builder("person")
            .fill {
                moveTo(8.3f, 8.2f)
                curveTo(8.3f, 6.157f, 9.957f, 4.5f, 12f, 4.5f)
                curveTo(14.043f, 4.5f, 15.7f, 6.157f, 15.7f, 8.2f)
                curveTo(15.7f, 10.243f, 14.043f, 11.9f, 12f, 11.9f)
                curveTo(9.957f, 11.9f, 8.3f, 10.243f, 8.3f, 8.2f)
                close()
                moveTo(4.4f, 20.6f)
                curveTo(4.4f, 16.2f, 7.8f, 13.7f, 12f, 13.7f)
                curveTo(16.2f, 13.7f, 19.6f, 16.2f, 19.6f, 20.6f)
                close()
            }
            .build()
    }

    /** A fat ring and a fat handle. The ring is punched rather than stroked so its weight matches the solid glyphs beside it. */
    val search: ImageVector by lazy {
        builder("search")
            .punch {
                moveTo(3.4f, 10.4f)
                curveTo(3.4f, 6.534f, 6.534f, 3.4f, 10.4f, 3.4f)
                curveTo(14.266f, 3.4f, 17.4f, 6.534f, 17.4f, 10.4f)
                curveTo(17.4f, 14.266f, 14.266f, 17.4f, 10.4f, 17.4f)
                curveTo(6.534f, 17.4f, 3.4f, 14.266f, 3.4f, 10.4f)
                close()
                moveTo(6.4f, 10.4f)
                curveTo(6.4f, 8.191f, 8.191f, 6.4f, 10.4f, 6.4f)
                curveTo(12.609f, 6.4f, 14.4f, 8.191f, 14.4f, 10.4f)
                curveTo(14.4f, 12.609f, 12.609f, 14.4f, 10.4f, 14.4f)
                curveTo(8.191f, 14.4f, 6.4f, 12.609f, 6.4f, 10.4f)
                close()
            }
            .stroke {
                moveTo(15.3f, 15.3f)
                lineTo(19.9f, 19.9f)
            }
            .build()
    }

    /** Three narrowing slabs: filtering as a funnel, without the sliders Material draws. */
    val filters: ImageVector by lazy {
        builder("filters")
            .fill {
                moveTo(4.65f, 5.9f)
                lineTo(19.35f, 5.9f)
                curveTo(20.04f, 5.9f, 20.6f, 6.46f, 20.6f, 7.15f)
                lineTo(20.6f, 7.15f)
                curveTo(20.6f, 7.84f, 20.04f, 8.4f, 19.35f, 8.4f)
                lineTo(4.65f, 8.4f)
                curveTo(3.96f, 8.4f, 3.4f, 7.84f, 3.4f, 7.15f)
                lineTo(3.4f, 7.15f)
                curveTo(3.4f, 6.46f, 3.96f, 5.9f, 4.65f, 5.9f)
                close()
                moveTo(7.35f, 10.75f)
                lineTo(16.65f, 10.75f)
                curveTo(17.34f, 10.75f, 17.9f, 11.31f, 17.9f, 12f)
                lineTo(17.9f, 12f)
                curveTo(17.9f, 12.69f, 17.34f, 13.25f, 16.65f, 13.25f)
                lineTo(7.35f, 13.25f)
                curveTo(6.66f, 13.25f, 6.1f, 12.69f, 6.1f, 12f)
                lineTo(6.1f, 12f)
                curveTo(6.1f, 11.31f, 6.66f, 10.75f, 7.35f, 10.75f)
                close()
                moveTo(10.15f, 15.6f)
                lineTo(13.85f, 15.6f)
                curveTo(14.54f, 15.6f, 15.1f, 16.16f, 15.1f, 16.85f)
                lineTo(15.1f, 16.85f)
                curveTo(15.1f, 17.54f, 14.54f, 18.1f, 13.85f, 18.1f)
                lineTo(10.15f, 18.1f)
                curveTo(9.46f, 18.1f, 8.9f, 17.54f, 8.9f, 16.85f)
                lineTo(8.9f, 16.85f)
                curveTo(8.9f, 16.16f, 9.46f, 15.6f, 10.15f, 15.6f)
                close()
            }
            .build()
    }

    /** A ribbon with its middle punched out, so the unsaved state is heavy without being solid. */
    val bookmark: ImageVector by lazy {
        builder("bookmark")
            .punch {
                moveTo(5.2f, 3.2f)
                lineTo(18.8f, 3.2f)
                lineTo(18.8f, 21f)
                lineTo(12f, 15.9f)
                lineTo(5.2f, 21f)
                close()
                moveTo(7.9f, 5.9f)
                lineTo(16.1f, 5.9f)
                lineTo(16.1f, 15.6f)
                lineTo(12f, 12.5f)
                lineTo(7.9f, 15.6f)
                close()
            }
            .build()
    }

    /** Saved: the same ribbon, filled in. */
    val bookmarkFilled: ImageVector by lazy {
        builder("bookmarkFilled")
            .fill {
                moveTo(5.2f, 3.2f)
                lineTo(18.8f, 3.2f)
                lineTo(18.8f, 21f)
                lineTo(12f, 15.9f)
                lineTo(5.2f, 21f)
                close()
            }
            .build()
    }

    val plus: ImageVector by lazy {
        builder("plus")
            .fill {
                moveTo(12f, 4.6f)
                lineTo(12f, 4.6f)
                curveTo(12.746f, 4.6f, 13.35f, 5.204f, 13.35f, 5.95f)
                lineTo(13.35f, 18.05f)
                curveTo(13.35f, 18.796f, 12.746f, 19.4f, 12f, 19.4f)
                lineTo(12f, 19.4f)
                curveTo(11.254f, 19.4f, 10.65f, 18.796f, 10.65f, 18.05f)
                lineTo(10.65f, 5.95f)
                curveTo(10.65f, 5.204f, 11.254f, 4.6f, 12f, 4.6f)
                close()
                moveTo(5.95f, 10.65f)
                lineTo(18.05f, 10.65f)
                curveTo(18.796f, 10.65f, 19.4f, 11.254f, 19.4f, 12f)
                lineTo(19.4f, 12f)
                curveTo(19.4f, 12.746f, 18.796f, 13.35f, 18.05f, 13.35f)
                lineTo(5.95f, 13.35f)
                curveTo(5.204f, 13.35f, 4.6f, 12.746f, 4.6f, 12f)
                lineTo(4.6f, 12f)
                curveTo(4.6f, 11.254f, 5.204f, 10.65f, 5.95f, 10.65f)
                close()
            }
            .build()
    }

    /** The app's own mark at icon size: the launcher pin, the map pin and this glyph are one shape, down to the punched hole. */
    val pin: ImageVector by lazy {
        builder("pin")
            .punch {
                moveTo(12f, 21f)
                curveTo(12f, 21f, 4.6f, 13.6f, 4.6f, 9.4f)
                curveTo(4.6f, 5.4f, 7.9f, 2.6f, 12f, 2.6f)
                curveTo(16.1f, 2.6f, 19.4f, 5.4f, 19.4f, 9.4f)
                curveTo(19.4f, 13.6f, 12f, 21f, 12f, 21f)
                close()
                moveTo(9f, 9.4f)
                curveTo(9f, 7.743f, 10.343f, 6.4f, 12f, 6.4f)
                curveTo(13.657f, 6.4f, 15f, 7.743f, 15f, 9.4f)
                curveTo(15f, 11.057f, 13.657f, 12.4f, 12f, 12.4f)
                curveTo(10.343f, 12.4f, 9f, 11.057f, 9f, 9.4f)
                close()
            }
            .build()
    }

    /** A fat ring around a solid centre, with four ticks. The dot is what says «you». */
    val myLocation: ImageVector by lazy {
        builder("myLocation")
            .punch {
                moveTo(6.6f, 12f)
                curveTo(6.6f, 9.018f, 9.018f, 6.6f, 12f, 6.6f)
                curveTo(14.982f, 6.6f, 17.4f, 9.018f, 17.4f, 12f)
                curveTo(17.4f, 14.982f, 14.982f, 17.4f, 12f, 17.4f)
                curveTo(9.018f, 17.4f, 6.6f, 14.982f, 6.6f, 12f)
                close()
                moveTo(8.6f, 12f)
                curveTo(8.6f, 10.122f, 10.122f, 8.6f, 12f, 8.6f)
                curveTo(13.878f, 8.6f, 15.4f, 10.122f, 15.4f, 12f)
                curveTo(15.4f, 13.878f, 13.878f, 15.4f, 12f, 15.4f)
                curveTo(10.122f, 15.4f, 8.6f, 13.878f, 8.6f, 12f)
                close()
            }
            .fill {
                moveTo(10.1f, 12f)
                curveTo(10.1f, 10.951f, 10.951f, 10.1f, 12f, 10.1f)
                curveTo(13.049f, 10.1f, 13.9f, 10.951f, 13.9f, 12f)
                curveTo(13.9f, 13.049f, 13.049f, 13.9f, 12f, 13.9f)
                curveTo(10.951f, 13.9f, 10.1f, 13.049f, 10.1f, 12f)
                close()
                moveTo(12f, 2.4f)
                lineTo(12f, 2.4f)
                curveTo(12.552f, 2.4f, 13f, 2.848f, 13f, 3.4f)
                lineTo(13f, 5f)
                curveTo(13f, 5.552f, 12.552f, 6f, 12f, 6f)
                lineTo(12f, 6f)
                curveTo(11.448f, 6f, 11f, 5.552f, 11f, 5f)
                lineTo(11f, 3.4f)
                curveTo(11f, 2.848f, 11.448f, 2.4f, 12f, 2.4f)
                close()
                moveTo(12f, 18f)
                lineTo(12f, 18f)
                curveTo(12.552f, 18f, 13f, 18.448f, 13f, 19f)
                lineTo(13f, 20.6f)
                curveTo(13f, 21.152f, 12.552f, 21.6f, 12f, 21.6f)
                lineTo(12f, 21.6f)
                curveTo(11.448f, 21.6f, 11f, 21.152f, 11f, 20.6f)
                lineTo(11f, 19f)
                curveTo(11f, 18.448f, 11.448f, 18f, 12f, 18f)
                close()
                moveTo(3.4f, 11f)
                lineTo(5f, 11f)
                curveTo(5.552f, 11f, 6f, 11.448f, 6f, 12f)
                lineTo(6f, 12f)
                curveTo(6f, 12.552f, 5.552f, 13f, 5f, 13f)
                lineTo(3.4f, 13f)
                curveTo(2.848f, 13f, 2.4f, 12.552f, 2.4f, 12f)
                lineTo(2.4f, 12f)
                curveTo(2.4f, 11.448f, 2.848f, 11f, 3.4f, 11f)
                close()
                moveTo(19f, 11f)
                lineTo(20.6f, 11f)
                curveTo(21.152f, 11f, 21.6f, 11.448f, 21.6f, 12f)
                lineTo(21.6f, 12f)
                curveTo(21.6f, 12.552f, 21.152f, 13f, 20.6f, 13f)
                lineTo(19f, 13f)
                curveTo(18.448f, 13f, 18f, 12.552f, 18f, 12f)
                lineTo(18f, 12f)
                curveTo(18f, 11.448f, 18.448f, 11f, 19f, 11f)
                close()
            }
            .build()
    }

    /** Four solid brackets closing on a dot: framing the city again after panning away. */
    val recenter: ImageVector by lazy {
        builder("recenter")
            .fill {
                moveTo(9.4f, 12f)
                curveTo(9.4f, 10.564f, 10.564f, 9.4f, 12f, 9.4f)
                curveTo(13.436f, 9.4f, 14.6f, 10.564f, 14.6f, 12f)
                curveTo(14.6f, 13.436f, 13.436f, 14.6f, 12f, 14.6f)
                curveTo(10.564f, 14.6f, 9.4f, 13.436f, 9.4f, 12f)
                close()
                moveTo(3.2f, 9.6f)
                lineTo(3.2f, 5.6f)
                curveTo(3.2f, 4.3f, 4.3f, 3.2f, 5.6f, 3.2f)
                lineTo(9.6f, 3.2f)
                lineTo(9.6f, 5.8f)
                lineTo(5.8f, 5.8f)
                lineTo(5.8f, 9.6f)
                close()
                moveTo(20.8f, 9.6f)
                lineTo(20.8f, 5.6f)
                curveTo(20.8f, 4.3f, 19.7f, 3.2f, 18.4f, 3.2f)
                lineTo(14.4f, 3.2f)
                lineTo(14.4f, 5.8f)
                lineTo(18.2f, 5.8f)
                lineTo(18.2f, 9.6f)
                close()
                moveTo(3.2f, 14.4f)
                lineTo(3.2f, 18.4f)
                curveTo(3.2f, 19.7f, 4.3f, 20.8f, 5.6f, 20.8f)
                lineTo(9.6f, 20.8f)
                lineTo(9.6f, 18.2f)
                lineTo(5.8f, 18.2f)
                lineTo(5.8f, 14.4f)
                close()
                moveTo(20.8f, 14.4f)
                lineTo(20.8f, 18.4f)
                curveTo(20.8f, 19.7f, 19.7f, 20.8f, 18.4f, 20.8f)
                lineTo(14.4f, 20.8f)
                lineTo(14.4f, 18.2f)
                lineTo(18.2f, 18.2f)
                lineTo(18.2f, 14.4f)
                close()
            }
            .build()
    }

    /** A four-point star with concave sides — an invitation, not a rating. */
    val sparkle: ImageVector by lazy {
        builder("sparkle")
            .fill {
                moveTo(12f, 2.8f)
                curveTo(12.9f, 8.7f, 15.3f, 11.1f, 21.2f, 12f)
                curveTo(15.3f, 12.9f, 12.9f, 15.3f, 12f, 21.2f)
                curveTo(11.1f, 15.3f, 8.7f, 12.9f, 2.8f, 12f)
                curveTo(8.7f, 11.1f, 11.1f, 8.7f, 12f, 2.8f)
                close()
            }
            .build()
    }

    /** A solid body with the keyhole punched through, under a fat shackle. */
    val lock: ImageVector by lazy {
        builder("lock")
            .punch {
                moveTo(7.8f, 10.1f)
                lineTo(16.2f, 10.1f)
                curveTo(17.967f, 10.1f, 19.4f, 11.533f, 19.4f, 13.3f)
                lineTo(19.4f, 17.5f)
                curveTo(19.4f, 19.267f, 17.967f, 20.7f, 16.2f, 20.7f)
                lineTo(7.8f, 20.7f)
                curveTo(6.033f, 20.7f, 4.6f, 19.267f, 4.6f, 17.5f)
                lineTo(4.6f, 13.3f)
                curveTo(4.6f, 11.533f, 6.033f, 10.1f, 7.8f, 10.1f)
                close()
                moveTo(10.3f, 15.4f)
                curveTo(10.3f, 14.461f, 11.061f, 13.7f, 12f, 13.7f)
                curveTo(12.939f, 13.7f, 13.7f, 14.461f, 13.7f, 15.4f)
                curveTo(13.7f, 16.339f, 12.939f, 17.1f, 12f, 17.1f)
                curveTo(11.061f, 17.1f, 10.3f, 16.339f, 10.3f, 15.4f)
                close()
            }
            .stroke {
                moveTo(8.3f, 10.2f)
                lineTo(8.3f, 7.8f)
                curveTo(8.3f, 5.7f, 9.9f, 4.1f, 12f, 4.1f)
                curveTo(14.1f, 4.1f, 15.7f, 5.7f, 15.7f, 7.8f)
                lineTo(15.7f, 10.2f)
            }
            .build()
    }

    val checkCircle: ImageVector by lazy {
        builder("checkCircle")
            .punch {
                moveTo(3.4f, 12f)
                curveTo(3.4f, 7.25f, 7.25f, 3.4f, 12f, 3.4f)
                curveTo(16.75f, 3.4f, 20.6f, 7.25f, 20.6f, 12f)
                curveTo(20.6f, 16.75f, 16.75f, 20.6f, 12f, 20.6f)
                curveTo(7.25f, 20.6f, 3.4f, 16.75f, 3.4f, 12f)
                close()
                moveTo(5.8f, 12f)
                curveTo(5.8f, 8.576f, 8.576f, 5.8f, 12f, 5.8f)
                curveTo(15.424f, 5.8f, 18.2f, 8.576f, 18.2f, 12f)
                curveTo(18.2f, 15.424f, 15.424f, 18.2f, 12f, 18.2f)
                curveTo(8.576f, 18.2f, 5.8f, 15.424f, 5.8f, 12f)
                close()
            }
            .stroke {
                moveTo(8.2f, 12.2f)
                lineTo(10.9f, 14.9f)
                lineTo(15.9f, 9.4f)
            }
            .build()
    }

    val alert: ImageVector by lazy {
        builder("alert")
            .punch {
                moveTo(3.4f, 12f)
                curveTo(3.4f, 7.25f, 7.25f, 3.4f, 12f, 3.4f)
                curveTo(16.75f, 3.4f, 20.6f, 7.25f, 20.6f, 12f)
                curveTo(20.6f, 16.75f, 16.75f, 20.6f, 12f, 20.6f)
                curveTo(7.25f, 20.6f, 3.4f, 16.75f, 3.4f, 12f)
                close()
                moveTo(5.8f, 12f)
                curveTo(5.8f, 8.576f, 8.576f, 5.8f, 12f, 5.8f)
                curveTo(15.424f, 5.8f, 18.2f, 8.576f, 18.2f, 12f)
                curveTo(18.2f, 15.424f, 15.424f, 18.2f, 12f, 18.2f)
                curveTo(8.576f, 18.2f, 5.8f, 15.424f, 5.8f, 12f)
                close()
            }
            .fill {
                moveTo(12f, 7f)
                lineTo(12f, 7f)
                curveTo(12.718f, 7f, 13.3f, 7.582f, 13.3f, 8.3f)
                lineTo(13.3f, 12.3f)
                curveTo(13.3f, 13.018f, 12.718f, 13.6f, 12f, 13.6f)
                lineTo(12f, 13.6f)
                curveTo(11.282f, 13.6f, 10.7f, 13.018f, 10.7f, 12.3f)
                lineTo(10.7f, 8.3f)
                curveTo(10.7f, 7.582f, 11.282f, 7f, 12f, 7f)
                close()
                moveTo(10.45f, 16.4f)
                curveTo(10.45f, 15.544f, 11.144f, 14.85f, 12f, 14.85f)
                curveTo(12.856f, 14.85f, 13.55f, 15.544f, 13.55f, 16.4f)
                curveTo(13.55f, 17.256f, 12.856f, 17.95f, 12f, 17.95f)
                curveTo(11.144f, 17.95f, 10.45f, 17.256f, 10.45f, 16.4f)
                close()
            }
            .build()
    }

    val clock: ImageVector by lazy {
        builder("clock")
            .punch {
                moveTo(3.4f, 12f)
                curveTo(3.4f, 7.25f, 7.25f, 3.4f, 12f, 3.4f)
                curveTo(16.75f, 3.4f, 20.6f, 7.25f, 20.6f, 12f)
                curveTo(20.6f, 16.75f, 16.75f, 20.6f, 12f, 20.6f)
                curveTo(7.25f, 20.6f, 3.4f, 16.75f, 3.4f, 12f)
                close()
                moveTo(5.8f, 12f)
                curveTo(5.8f, 8.576f, 8.576f, 5.8f, 12f, 5.8f)
                curveTo(15.424f, 5.8f, 18.2f, 8.576f, 18.2f, 12f)
                curveTo(18.2f, 15.424f, 15.424f, 18.2f, 12f, 18.2f)
                curveTo(8.576f, 18.2f, 5.8f, 15.424f, 5.8f, 12f)
                close()
            }
            .stroke {
                moveTo(12f, 7.4f)
                lineTo(12f, 12f)
                lineTo(15.4f, 14.1f)
            }
            .build()
    }

    /** A solid hourglass for the waiting list: time passing, not an error. */
    val queue: ImageVector by lazy {
        builder("queue")
            .fill {
                moveTo(7.55f, 3f)
                lineTo(16.45f, 3f)
                curveTo(17.085f, 3f, 17.6f, 3.515f, 17.6f, 4.15f)
                lineTo(17.6f, 4.15f)
                curveTo(17.6f, 4.785f, 17.085f, 5.3f, 16.45f, 5.3f)
                lineTo(7.55f, 5.3f)
                curveTo(6.915f, 5.3f, 6.4f, 4.785f, 6.4f, 4.15f)
                lineTo(6.4f, 4.15f)
                curveTo(6.4f, 3.515f, 6.915f, 3f, 7.55f, 3f)
                close()
                moveTo(7.55f, 18.7f)
                lineTo(16.45f, 18.7f)
                curveTo(17.085f, 18.7f, 17.6f, 19.215f, 17.6f, 19.85f)
                lineTo(17.6f, 19.85f)
                curveTo(17.6f, 20.485f, 17.085f, 21f, 16.45f, 21f)
                lineTo(7.55f, 21f)
                curveTo(6.915f, 21f, 6.4f, 20.485f, 6.4f, 19.85f)
                lineTo(6.4f, 19.85f)
                curveTo(6.4f, 19.215f, 6.915f, 18.7f, 7.55f, 18.7f)
                close()
                moveTo(8.2f, 5.3f)
                lineTo(15.8f, 5.3f)
                lineTo(12.7f, 12f)
                lineTo(15.8f, 18.7f)
                lineTo(8.2f, 18.7f)
                lineTo(11.3f, 12f)
                close()
            }
            .build()
    }

    private fun builder(name: String) =
        ImageVector.Builder("Poruch.$name", SIZE.dp, SIZE.dp, SIZE, SIZE)

    private inline fun ImageVector.Builder.stroke(block: androidx.compose.ui.graphics.vector.PathBuilder.() -> Unit) =
        path(
            stroke = SolidColor(Color.Black), strokeLineWidth = STROKE,
            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,
            pathBuilder = block
        )

    private inline fun ImageVector.Builder.fill(block: androidx.compose.ui.graphics.vector.PathBuilder.() -> Unit) =
        path(fill = SolidColor(Color.Black), pathBuilder = block)

    /** One path whose inner subpaths punch holes through the outer one. */
    private inline fun ImageVector.Builder.punch(block: androidx.compose.ui.graphics.vector.PathBuilder.() -> Unit) =
        path(fill = SolidColor(Color.Black), pathFillType = PathFillType.EvenOdd, pathBuilder = block)
}

private const val SIZE = 24f
private const val STROKE = 2.6f
